import type {CommercialBundle} from "../evidence/commercial.js";
import type {CandidateStrategy} from "../decisions/types.js";
import {synthesizeEvaluations} from "./synthesis.js";
const sum=(bundle:CommercialBundle,key:"spend"|"pipeline"|"revenue"|"keyEvents")=>bundle.evidence.reduce((total,row)=>total+Number(row.metrics[key]??0),0);
export function executiveCandidates(bundle:CommercialBundle):CandidateStrategy[]{const spend=sum(bundle,"spend"),pipeline=sum(bundle,"pipeline"),revenue=sum(bundle,"revenue"),events=sum(bundle,"keyEvents"),commercial=pipeline+revenue>0,measured=commercial||events>0;return [
 {id:"scale_controlled",name:"Controlled scale",summary:"Increase investment only in commercially evidenced segments.",expectedUpside:"More qualified pipeline without an unbounded commitment",downside:"Higher spend and saturation risk",assumptions:["Observed demand is incremental","CRM attribution is materially correct"],riskLevel:commercial?"medium":"high",reversibility:"medium",growthScore:commercial?.86:.48,financeScore:revenue>spend?.82:.46,brandScore:.62,customerScore:.64,measurementScore:commercial?.72:.38},
 {id:"validate_first",name:"Validate before scaling",summary:"Run a bounded holdout or funnel-quality experiment.",expectedUpside:"Causal and downstream-quality clarity",downside:"Slower near-term volume",assumptions:["A valid comparison can be constructed","The review window covers conversion lag"],riskLevel:"low",reversibility:"high",growthScore:.62,financeScore:.82,brandScore:.7,customerScore:.75,measurementScore:measured?.94:.8},
 {id:"hold",name:"Hold current allocation",summary:"Make no material allocation change while repairing evidence gaps.",expectedUpside:"Avoids scaling noise or broken measurement",downside:"May delay a real opportunity",assumptions:["Evidence gaps are decision material"],riskLevel:"low",reversibility:"high",growthScore:measured?.42:.68,financeScore:.88,brandScore:.72,customerScore:.58,measurementScore:measured?.66:.9}
 ];}
export function evaluateExecutiveBundle(bundle:CommercialBundle,objective="profitable, durable growth"){const constraints=[...new Set(bundle.warnings.slice(0,5))],options=executiveCandidates(bundle),synthesis=synthesizeEvaluations(options,{evidence:{sources:[...new Set(bundle.evidence.map(row=>row.source))]},constraints,objective});return {options,synthesis}}
export function renderEvaluationSynthesis(result:ReturnType<typeof evaluateExecutiveBundle>){const {synthesis}=result;return `## Independent evaluator council\n\n**Recommendation:** ${synthesis.finalRecommendation}  \n**Disagreement:** ${synthesis.disagreements.join("; ")||"No material vote disagreement"}  \n**Unresolved tensions:** ${synthesis.unresolvedTensions.join("; ")||"None recorded"}  \n**What would change it:** ${synthesis.whatWouldChangeRecommendation.join("; ")}\n\n${synthesis.evaluations.map(row=>`- **${row.evaluator}:** ${row.preferredOption} (${row.confidence}); ${row.reasoning}`).join("\n")}`}
