import {randomUUID} from "node:crypto";
import type {ClosedLoopLearningRecord,DecisionRecord,OutcomeRecord} from "./types.js";
import {createDecision,deriveLearning,listDecisions,recordOutcome,relevantLearning} from "./store.js";
import {PostgresDecisionRepository} from "./postgres.js";
import {emitTelemetry} from "../observability/telemetry.js";
import {validateNumericClaims} from "../measurement/numericProvenance.js";
const safe=(value:string)=>value.replace(/[^a-zA-Z0-9_.-]/g,"_").slice(0,100);
const postgres=()=>Boolean(process.env.DECISION_DATABASE_URL);
async function withRepository<T>(work:(repo:PostgresDecisionRepository)=>Promise<T>){const repo=new PostgresDecisionRepository();try{await repo.migrate();return await work(repo)}finally{await repo.close()}}
export async function createDecisionRecord(input:Omit<DecisionRecord,"id"|"createdAt"|"tenantId"|"accountId">,tenantId="local",accountId="default"){if(!postgres())return createDecision(input,tenantId,accountId);const row:DecisionRecord={...input,id:`dec_${randomUUID()}`,createdAt:new Date().toISOString(),tenantId:safe(tenantId),accountId:safe(accountId)};await withRepository(repo=>repo.insert("decision",row));emitTelemetry("decision_created",{decisionId:row.id,tenantId:row.tenantId,accountId:row.accountId,storage:"postgres"});return row}
export async function listDecisionRecords(accountId="default",tenantId="local",limit=20){if(!postgres())return listDecisions(accountId,tenantId,limit);return withRepository(repo=>repo.list<DecisionRecord>("decision",safe(tenantId),safe(accountId),limit))}
export async function recordOutcomeRecord(input:Omit<OutcomeRecord,"id"|"tenantId"|"accountId">,tenantId="local",accountId="default"){if(!postgres())return recordOutcome(input,tenantId,accountId);const known=new Set(input.actualMetrics.flatMap(claim=>claim.evidenceIds??[])),validation=validateNumericClaims(input.actualMetrics,known);if(!validation.valid)throw new Error(validation.errors.join("; "));const tenant=safe(tenantId),account=safe(accountId),decisions=await withRepository(repo=>repo.list<DecisionRecord>("decision",tenant,account,1000));if(!decisions.some(row=>row.id===input.decisionId))throw new Error("Decision not found in tenant/account scope");const row:OutcomeRecord={...input,id:`out_${randomUUID()}`,tenantId:tenant,accountId:account};await withRepository(repo=>repo.insert("outcome",row));emitTelemetry("outcome_recorded",{decisionId:row.decisionId,outcomeId:row.id,tenantId:tenant,accountId:account,storage:"postgres"});return row}
export async function deriveLearningRecord(decisionId:string,tenantId="local",accountId="default"){if(!postgres())return deriveLearning(decisionId,tenantId,accountId);const tenant=safe(tenantId),account=safe(accountId),[decisions,outcomes,prior]=await withRepository(async repo=>Promise.all([repo.list<DecisionRecord>("decision",tenant,account,1000),repo.list<OutcomeRecord>("outcome",tenant,account,1000),repo.list<ClosedLoopLearningRecord>("learning",tenant,account,1000)])),decision=decisions.find(row=>row.id===decisionId),matching=outcomes.filter(row=>row.decisionId===decisionId).sort((a,b)=>a.measuredAt.localeCompare(b.measuredAt));if(!decision)throw new Error("Decision not found in tenant/account scope");if(!matching.length)throw new Error("Learning requires an explicit recorded outcome");const latest=matching.at(-1)!,direction=latest.observedOutcome==="positive"?1:latest.observedOutcome==="negative"?-1:0,priorDirection=prior.filter(row=>row.decisionId===decisionId).reduce((sum,row)=>sum+Math.sign(row.confidenceChange),0),contradiction=priorDirection!==0&&direction!==0&&Math.sign(priorDirection)!==direction,row:ClosedLoopLearningRecord={id:`learn_${randomUUID()}`,tenantId:tenant,accountId:account,decisionId,lesson:latest.lessons.join("; ")||`Recorded ${latest.observedOutcome} outcome for ${decision.recommendation}`,appliesTo:decision.candidateStrategies.map(x=>x.id),confidenceChange:contradiction?direction*.25:direction*.15,positiveEvidence:direction>0?latest.actualMetrics.map(x=>x.label):[],negativeEvidence:direction<0?latest.actualMetrics.map(x=>x.label):[],createdAt:new Date().toISOString()};await withRepository(repo=>repo.insert("learning",row));emitTelemetry("learning_updated",{decisionId,learningId:row.id,tenantId:tenant,accountId:account,storage:"postgres"});return row}
export async function inspectLearningRecords(accountId="default",tenantId="local",limit=20){if(!postgres())return {learning:relevantLearning(accountId,tenantId,limit),decisions:listDecisions(accountId,tenantId,limit)};return withRepository(async repo=>({learning:await repo.list<ClosedLoopLearningRecord>("learning",safe(tenantId),safe(accountId),limit),decisions:await repo.list<DecisionRecord>("decision",safe(tenantId),safe(accountId),limit)}))}
