import {randomUUID} from "node:crypto";
import {appendFileSync,chmodSync,existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname} from "node:path";
import type {ClosedLoopLearningRecord,DecisionRecord,OutcomeRecord} from "./types.js";
import {insertRecord,scopedRecords} from "./sqlite.js";
import {emitTelemetry} from "../observability/telemetry.js";
import {validateNumericClaims} from "../measurement/numericProvenance.js";
const safe=(value:string)=>value.replace(/[^a-zA-Z0-9_.-]/g,"_").slice(0,100);
const append=<T>(path:string,row:T)=>{mkdirSync(dirname(path),{recursive:true,mode:0o700});if(!existsSync(path))writeFileSync(path,"",{mode:0o600});appendFileSync(path,`${JSON.stringify(row)}\n`,{mode:0o600});chmodSync(path,0o600);return row};
const read=<T>(path:string):T[]=>existsSync(path)?readFileSync(path,"utf8").split("\n").filter(Boolean).map(x=>JSON.parse(x) as T):[];
const scoped=<T extends {tenantId:string;accountId:string}>(kind:"decisions"|"outcomes"|"learning",tenant:string,account:string,path?:string,decisionId?:string)=>path?read<T>(path).filter(x=>x.tenantId===tenant&&x.accountId===account&&(!decisionId||("decisionId" in x&&(x as T&{decisionId:string}).decisionId===decisionId))):scopedRecords<T>(kind,tenant,account,decisionId);
const persist=<T extends {id:string;tenantId:string;accountId:string}>(kind:"decisions"|"outcomes"|"learning",row:T,path?:string)=>path?append(path,row):insertRecord(kind,row as T&{createdAt?:string;measuredAt?:string;decisionId?:string});
export function createDecision(input:Omit<DecisionRecord,"id"|"createdAt"|"tenantId"|"accountId">,tenantId="local",accountId="default",path?:string){const row:DecisionRecord={...input,id:`dec_${randomUUID()}`,createdAt:new Date().toISOString(),tenantId:safe(tenantId),accountId:safe(accountId)};persist("decisions",row,path);emitTelemetry("decision_created",{decisionId:row.id,tenantId:row.tenantId,accountId:row.accountId,evidenceSnapshotIds:row.evidenceSnapshotIds});return row}
export function listDecisions(accountId="default",tenantId="local",limit=20,path?:string){return scoped<DecisionRecord>("decisions",safe(tenantId),safe(accountId),path).slice(-Math.min(100,Math.max(1,limit))).reverse()}
export function recordOutcome(input:Omit<OutcomeRecord,"id"|"tenantId"|"accountId">,tenantId="local",accountId="default",paths?:{decisions?:string;outcomes?:string}){const tenant=safe(tenantId),account=safe(accountId),decision=scoped<DecisionRecord>("decisions",tenant,account,paths?.decisions).find(x=>x.id===input.decisionId);if(!decision)throw new Error("Decision not found in tenant/account scope");const known=new Set(input.actualMetrics.flatMap(claim=>claim.evidenceIds??[])),validation=validateNumericClaims(input.actualMetrics,known);if(!validation.valid)throw new Error(validation.errors.join("; "));const row:OutcomeRecord={...input,id:`out_${randomUUID()}`,tenantId:tenant,accountId:account};persist("outcomes",row,paths?.outcomes);emitTelemetry("outcome_recorded",{decisionId:row.decisionId,outcomeId:row.id,tenantId:row.tenantId,accountId:row.accountId,status:row.status});return row}
export function deriveLearning(decisionId:string,tenantId="local",accountId="default",paths?:{decisions?:string;outcomes?:string;learning?:string}){const tenant=safe(tenantId),account=safe(accountId),decision=scoped<DecisionRecord>("decisions",tenant,account,paths?.decisions).find(x=>x.id===decisionId),outcomes=scoped<OutcomeRecord>("outcomes",tenant,account,paths?.outcomes,decisionId);if(!decision)throw new Error("Decision not found in tenant/account scope");if(!outcomes.length)throw new Error("Learning requires an explicit recorded outcome");const latest=outcomes.at(-1)!,direction=latest.observedOutcome==="positive"?1:latest.observedOutcome==="negative"?-1:0,prior=scoped<ClosedLoopLearningRecord>("learning",tenant,account,paths?.learning,decisionId),priorDirection=prior.reduce((sum,x)=>sum+Math.sign(x.confidenceChange),0),contradiction=priorDirection!==0&&direction!==0&&Math.sign(priorDirection)!==direction,change=contradiction?direction*.25:direction*.15;const row:ClosedLoopLearningRecord={id:`learn_${randomUUID()}`,tenantId:tenant,decisionId,accountId:account,lesson:latest.lessons.join("; ")||`Recorded ${latest.observedOutcome} outcome for ${decision.recommendation}`,appliesTo:decision.candidateStrategies.map(x=>x.id),confidenceChange:change,positiveEvidence:latest.observedOutcome==="positive"?latest.actualMetrics.map(x=>x.label):[],negativeEvidence:latest.observedOutcome==="negative"?latest.actualMetrics.map(x=>x.label):[],createdAt:new Date().toISOString()};persist("learning",row,paths?.learning);emitTelemetry("learning_updated",{decisionId,learningId:row.id,tenantId:tenant,accountId:account,confidenceChange:change});return row}
export function relevantLearning(accountId="default",tenantId="local",limit=10,path?:string){return scoped<ClosedLoopLearningRecord>("learning",safe(tenantId),safe(accountId),path).slice(-limit).reverse()}
