import {randomUUID} from "node:crypto";
import {appendFileSync,chmodSync,existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,join} from "node:path";
import type {ClosedLoopLearningRecord,DecisionRecord,OutcomeRecord} from "./types.js";
import {emitTelemetry} from "../observability/telemetry.js";
const base=()=>process.env.MARKETING_DECISION_DIR??join(process.cwd(),".marketing-decisions");
const file=(name:string,path?:string)=>path??join(base(),`${name}.jsonl`);
const safe=(value:string)=>value.replace(/[^a-zA-Z0-9_.-]/g,"_").slice(0,100);
const append=<T>(path:string,row:T)=>{mkdirSync(dirname(path),{recursive:true,mode:0o700});if(!existsSync(path))writeFileSync(path,"",{mode:0o600});appendFileSync(path,`${JSON.stringify(row)}\n`,{mode:0o600});chmodSync(path,0o600);return row};
const read=<T>(path:string):T[]=>existsSync(path)?readFileSync(path,"utf8").split("\n").filter(Boolean).map(x=>JSON.parse(x) as T):[];
export function createDecision(input:Omit<DecisionRecord,"id"|"createdAt"|"tenantId"|"accountId">,tenantId="local",accountId="default",path?:string){const row:DecisionRecord={...input,id:`dec_${randomUUID()}`,createdAt:new Date().toISOString(),tenantId:safe(tenantId),accountId:safe(accountId)};append(file("decisions",path),row);emitTelemetry("decision_created",{decisionId:row.id,tenantId:row.tenantId,accountId:row.accountId,evidenceSnapshotIds:row.evidenceSnapshotIds});return row}
export function recordOutcome(input:Omit<OutcomeRecord,"id"|"tenantId"|"accountId">,tenantId="local",accountId="default",paths?:{decisions?:string;outcomes?:string}){const decision=read<DecisionRecord>(file("decisions",paths?.decisions)).find(x=>x.id===input.decisionId&&x.tenantId===safe(tenantId)&&x.accountId===safe(accountId));if(!decision)throw new Error("Decision not found in tenant/account scope");const row:OutcomeRecord={...input,id:`out_${randomUUID()}`,tenantId:safe(tenantId),accountId:safe(accountId)};append(file("outcomes",paths?.outcomes),row);emitTelemetry("outcome_recorded",{decisionId:row.decisionId,outcomeId:row.id,tenantId:row.tenantId,accountId:row.accountId,status:row.status});return row}
export function deriveLearning(decisionId:string,tenantId="local",accountId="default",paths?:{decisions?:string;outcomes?:string;learning?:string}){const tenant=safe(tenantId),account=safe(accountId),decision=read<DecisionRecord>(file("decisions",paths?.decisions)).find(x=>x.id===decisionId&&x.tenantId===tenant&&x.accountId===account),outcomes=read<OutcomeRecord>(file("outcomes",paths?.outcomes)).filter(x=>x.decisionId===decisionId&&x.tenantId===tenant&&x.accountId===account);if(!decision)throw new Error("Decision not found in tenant/account scope");if(!outcomes.length)throw new Error("Learning requires an explicit recorded outcome");const latest=outcomes.at(-1)!,direction=latest.observedOutcome==="positive"?1:latest.observedOutcome==="negative"?-1:0,prior=read<ClosedLoopLearningRecord>(file("learning",paths?.learning)).filter(x=>x.decisionId===decisionId&&x.tenantId===tenant&&x.accountId===account),priorDirection=prior.reduce((sum,x)=>sum+Math.sign(x.confidenceChange),0),contradiction=priorDirection!==0&&direction!==0&&Math.sign(priorDirection)!==direction,change=contradiction?direction*.25:direction*.15;
 const row:ClosedLoopLearningRecord={id:`learn_${randomUUID()}`,tenantId:tenant,decisionId,accountId:account,lesson:latest.lessons.join("; ")||`Recorded ${latest.observedOutcome} outcome for ${decision.recommendation}`,appliesTo:decision.candidateStrategies.map(x=>x.id),confidenceChange:change,positiveEvidence:latest.observedOutcome==="positive"?latest.actualMetrics.map(x=>x.label):[],negativeEvidence:latest.observedOutcome==="negative"?latest.actualMetrics.map(x=>x.label):[],createdAt:new Date().toISOString()};append(file("learning",paths?.learning),row);emitTelemetry("learning_updated",{decisionId,learningId:row.id,tenantId:tenant,accountId:account,confidenceChange:change});return row}
export function relevantLearning(accountId="default",tenantId="local",limit=10,path?:string){return read<ClosedLoopLearningRecord>(file("learning",path)).filter(x=>x.tenantId===safe(tenantId)&&x.accountId===safe(accountId)).slice(-limit)}
