import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { approve, createPreview, findByIdempotencyKey, finish, getApproval, history, payloadHash, revoke } from "./store.js";
import { actionAdapters, assertCanExecute, assertCanPreview, assertRiskPolicy, loadActionPolicy } from "./policy.js";
import type { ActionRequest } from "./types.js";
export const permissionStatus=()=>{const policy=loadActionPolicy();return {...policy,actionAdapters,guarantees:["Every execution requires a separate preview and exact approval phrase","Approvals expire and are single use","Payload integrity is checked before execution","External write adapters are disabled until explicitly implemented"]}};
export function previewAction(request:ActionRequest){const policy=loadActionPolicy();assertCanPreview(policy,request);assertRiskPolicy(request);if(request.idempotencyKey&&findByIdempotencyKey(request.idempotencyKey))throw new Error("Idempotency key already has an active or completed action");return createPreview(request,policy.approvalTtlMinutes)}
export const approveAction=(id:string,confirmation:string)=>approve(id,confirmation);
export const revokeAction=(id:string)=>revoke(id);
export const actionHistory=(limit:number)=>history(limit);
export async function executeAction(id:string){const record=getApproval(id);if(record.status!=="approved")throw new Error(`Action cannot execute because approval is ${record.status}`);if(payloadHash(record.request)!==record.payloadHash)throw new Error("Approved payload no longer matches its preview");assertCanExecute(loadActionPolicy(),record.request);try{assertRiskPolicy(record.request,"execute");if(record.request.kind!=="save_campaign_draft")throw new Error(`No write adapter is enabled for ${record.request.kind}; the approved action was not executed`);const directory=resolve(process.env.MARKETING_DRAFT_DIR??".marketing-actions/drafts");mkdirSync(directory,{recursive:true,mode:0o700});const path=join(directory,`${id}.json`);writeFileSync(path,`${JSON.stringify({approvalId:id,tenantId:record.request.tenantId??"local",accountId:record.request.accountId??"default",idempotencyKey:record.request.idempotencyKey,createdAt:new Date().toISOString(),...record.request.payload},null,2)}\n`,{mode:0o600,flag:"wx"});const result={executed:true,kind:record.request.kind,path,idempotencyKey:record.request.idempotencyKey};finish(id,"executed",result);return result}catch(error){finish(id,"failed",undefined,error instanceof Error?error.message:"Unknown execution error");throw error}}
