import { createHash, randomUUID } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { ActionRequest, ApprovalRecord } from "./types.js";
const root=()=>resolve(process.env.MCP_ACTION_DIR??".marketing-actions"),recordPath=(id:string)=>join(root(),"approvals",`${id}.json`),auditPath=()=>join(root(),"audit.jsonl");
const stable=(value:unknown):unknown=>Array.isArray(value)?value.map(stable):value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,stable(item)])):value;
export const payloadHash=(request:ActionRequest)=>createHash("sha256").update(JSON.stringify(stable(request))).digest("hex");
const prepare=()=>{mkdirSync(join(root(),"approvals"),{recursive:true,mode:0o700});chmodSync(root(),0o700)};
const save=(record:ApprovalRecord)=>{prepare();const path=recordPath(record.approvalId),temp=`${path}.${process.pid}.tmp`;writeFileSync(temp,`${JSON.stringify(record,null,2)}\n`,{mode:0o600});renameSync(temp,path);return record};
const audit=(event:Record<string,unknown>)=>{prepare();writeFileSync(auditPath(),`${JSON.stringify({timestamp:new Date().toISOString(),...event})}\n`,{flag:"a",mode:0o600})};
export function createPreview(request:ActionRequest,ttlMinutes:number){const now=new Date(),record:ApprovalRecord={version:1,approvalId:`apr_${randomUUID()}`,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+ttlMinutes*60000).toISOString(),status:"preview",payloadHash:payloadHash(request),request};save(record);audit({approvalId:record.approvalId,event:"preview_created",kind:request.kind,source:request.source});return record}
export function getApproval(id:string){if(!/^apr_[0-9a-f-]{36}$/.test(id))throw new Error("Invalid approval ID");const path=recordPath(id);if(!existsSync(path))throw new Error("Approval not found");const record=JSON.parse(readFileSync(path,"utf8")) as ApprovalRecord;if(record.status!=="executed"&&record.status!=="revoked"&&Date.parse(record.expiresAt)<=Date.now()){record.status="expired";save(record)}return record}
export function approve(id:string,confirmation:string){const record=getApproval(id);if(record.status!=="preview")throw new Error(`Approval is ${record.status}`);if(confirmation!==`APPROVE ${id}`)throw new Error(`Exact confirmation required: APPROVE ${id}`);if(payloadHash(record.request)!==record.payloadHash)throw new Error("Preview payload integrity check failed");record.status="approved";record.approvedAt=new Date().toISOString();save(record);audit({approvalId:id,event:"human_approval_recorded"});return record}
export function revoke(id:string){const record=getApproval(id);if(["executed","revoked","expired"].includes(record.status))throw new Error(`Approval is ${record.status}`);record.status="revoked";record.revokedAt=new Date().toISOString();save(record);audit({approvalId:id,event:"approval_revoked"});return record}
export function finish(id:string,status:"executed"|"failed",result?:Record<string,unknown>,error?:string){const record=getApproval(id);record.status=status;record.executedAt=new Date().toISOString();record.result=result;record.error=error;save(record);audit({approvalId:id,event:status,kind:record.request.kind,source:record.request.source,error});return record}
export function history(limit=20){prepare();return readdirSync(join(root(),"approvals")).filter(file=>file.endsWith(".json")).map(file=>JSON.parse(readFileSync(join(root(),"approvals",file),"utf8")) as ApprovalRecord).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,limit).map(record=>({approvalId:record.approvalId,kind:record.request.kind,source:record.request.source,summary:record.request.summary,status:record.status,createdAt:record.createdAt,expiresAt:record.expiresAt}))}
