const $=id=>document.getElementById(id),state={catalog:null,charts:JSON.parse(localStorage.getItem("gmi-dashboard")||"[]")},palette=["#176b4d","#3569d4","#ef7d42","#8b62b3","#c49a1a","#399d91"];
const geo={usa:[-100,38],unitedstates:[-100,38],ind:[78,22],india:[78,22],gbr:[-3,55],unitedkingdom:[-3,55],can:[-106,56],canada:[-106,56],aus:[134,-25],australia:[134,-25],deu:[10,51],germany:[10,51],fra:[2,46],france:[2,46],bra:[-52,-10],brazil:[-52,-10],jpn:[138,36],japan:[138,36],sgp:[104,1],singapore:[104,1],are:[54,24],unitedarabemirates:[54,24],nld:[5,52],netherlands:[5,52],esp:[-4,40],spain:[-4,40],ita:[12,42],italy:[12,42],mex:[-102,23],mexico:[-102,23],zaf:[24,-29],southafrica:[24,-29],idn:[118,-2],indonesia:[118,-2]};
const fmt=value=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2,notation:Math.abs(value)>=100000?"compact":"standard"}).format(value),escape=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char])),delta=(current,previous)=>previous?(current-previous)/Math.abs(previous):null;
function options(element,values,label=value=>value.replaceAll("_"," ")){element.innerHTML=values.map(value=>`<option value="${escape(value)}">${escape(label(value))}</option>`).join("")}
function syncDataset(){const item=state.catalog.datasets[$("dataset").value];options($("dimension"),item.dimensions);options($("metric"),item.metrics)}
function spec(){return {dataset:$("dataset").value,dimension:$("dimension").value,metric:$("metric").value,aggregation:$("aggregation").value,chart:$("chart").value,filter:$("filter").value,limit:Number($("limit").value),sort:$("sort").value,start_date:$("start_date").value||undefined,end_date:$("end_date").value||undefined,comparison:$("comparison").value,title:$("title").value}}
async function query(value){const response=await fetch("/api/query",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)}),result=await response.json();if(!response.ok)throw new Error(result.error);return result}
function geoChart(points){const located=points.map((point,index)=>{const key=point.label.toLowerCase().replace(/[^a-z]/g,"");return {point,coord:geo[key],color:palette[index%palette.length]}}).filter(item=>item.coord),max=Math.max(...located.map(item=>Math.abs(item.point.value)),1);if(!located.length)return '<p class="error">No supported country locations were found. Use a horizontal bar or table for this dataset.</p>';return `<svg viewBox="0 0 600 280" role="img" aria-label="Country bubble map"><rect width="600" height="280" rx="8" fill="#eef1eb"/>${[-120,-60,0,60,120].map(lon=>`<line x1="${(lon+180)/360*600}" y1="0" x2="${(lon+180)/360*600}" y2="280" stroke="#d9d4c7"/>`).join("")}${[-60,-30,0,30,60].map(lat=>`<line x1="0" y1="${(90-lat)/180*280}" x2="600" y2="${(90-lat)/180*280}" stroke="#d9d4c7"/>`).join("")}${located.map(({point,coord,color})=>`<circle cx="${(coord[0]+180)/360*600}" cy="${(90-coord[1])/180*280}" r="${7+Math.sqrt(Math.abs(point.value)/max)*19}" fill="${color}" opacity=".78"><title>${escape(point.label)}: ${fmt(point.value)}</title></circle>`).join("")}</svg><p class="map-note">Bubble size represents the selected metric. Use a table for countries without a local centroid.</p>`}
function chartHtml(type,points){if(!points.length)return '<p class="error">No evidence matched this view.</p>';const max=Math.max(...points.map(p=>Math.abs(p.value)),1),current=points.reduce((s,p)=>s+p.value,0),previous=points.reduce((s,p)=>s+(p.previousValue??0),0),change=delta(current,previous);
 if(type==="kpi")return `<div class="kpi"><strong>${fmt(current)}</strong><span>Previous: ${fmt(previous)}</span>${change===null?"":`<span class="delta ${change<0?"negative":""}">${change>=0?"+":""}${(change*100).toFixed(1)}%</span>`}</div>`;
 if(type==="table")return `<table><thead><tr><th>Group</th><th>Current</th><th>Previous</th><th>Change</th></tr></thead><tbody>${points.map(p=>{const change=delta(p.value,p.previousValue??0);return `<tr><td>${escape(p.label)}</td><td>${fmt(p.value)}</td><td>${p.previousValue===undefined?"—":fmt(p.previousValue)}</td><td>${change===null?"—":`${change>=0?"+":""}${(change*100).toFixed(1)}%`}</td></tr>`}).join("")}</tbody></table>`;
 if(type==="horizontal_bar")return `<div class="hbars">${points.map(p=>`<div class="hrow"><span title="${escape(p.label)}">${escape(p.label)}</span><div class="hbar" style="width:${Math.abs(p.value)/max*100}%"></div><b>${fmt(p.value)}</b></div>`).join("")}</div>`;
 if(type==="donut"){const total=points.reduce((s,p)=>s+Math.max(0,p.value),0)||1;let cursor=0;const stops=points.map((p,i)=>{const start=cursor;cursor+=Math.max(0,p.value)/total*100;return `${palette[i%palette.length]} ${start}% ${cursor}%`});return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops.join(",")})"></div><div class="legend">${points.slice(0,8).map((p,i)=>`<span><i style="background:${palette[i%palette.length]}"></i>${escape(p.label)} · ${fmt(p.value)}</span>`).join("")}</div></div>`}
 if(type==="geo")return geoChart(points);
 if(type==="line"||type==="area"){const width=600,height=210,coords=points.map((p,i)=>`${points.length===1?width/2:i/(points.length-1)*width},${height-Math.max(0,p.value)/max*(height-20)}`),prior=points.map((p,i)=>`${points.length===1?width/2:i/(points.length-1)*width},${height-Math.max(0,p.previousValue??0)/max*(height-20)}`),fill=type==="area"?`<polygon points="0,${height} ${coords.join(" ")} ${width},${height}" fill="#176b4d" opacity=".14"/>`:"";return `<svg viewBox="0 0 ${width} ${height}" role="img">${fill}<polyline points="${prior.join(" ")}" fill="none" stroke="#aeb5b0" stroke-width="3" stroke-dasharray="7 7"/><polyline points="${coords.join(" ")}" fill="none" stroke="#176b4d" stroke-width="4"/>${coords.map((c,i)=>{const [x,y]=c.split(",");return `<circle cx="${x}" cy="${y}" r="4" fill="#ef7d42"><title>${escape(points[i].label)}: ${fmt(points[i].value)}</title></circle>`}).join("")}</svg>`}
 return `<div class="bars">${points.map(p=>`<div class="bar-wrap"><div class="bar" style="height:${Math.abs(p.value)/max*88}%"><em>${fmt(p.value)}</em></div><span title="${escape(p.label)}">${escape(p.label)}</span></div>`).join("")}</div>`}
async function render(){const grid=$("grid");grid.innerHTML="";$("empty").hidden=state.charts.length>0;$("count").textContent=`${state.charts.length} chart${state.charts.length===1?"":"s"}`;for(const [index,item] of state.charts.entries()){const node=$("card").content.cloneNode(true),article=node.querySelector("article");node.querySelector("h3").textContent=item.title||`${item.metric.replaceAll("_"," ")} by ${item.dimension.replaceAll("_"," ")}`;node.querySelector(".meta").textContent=`${state.catalog.datasets[item.dataset]?.label??item.dataset} · ${item.aggregation} · ${item.chart.replaceAll("_"," ")}`;node.querySelector(".remove").onclick=()=>{state.charts.splice(index,1);save();render()};grid.append(node);try{const result=await query(item);article.querySelector(".viz").innerHTML=chartHtml(item.chart,result.points);const period=result.period?` · ${result.period.startDate} to ${result.period.endDate}`:"";article.querySelector(".foot").textContent=`${result.summary.matchedRows} matched rows${period} · calculated locally`}catch(error){article.querySelector(".viz").innerHTML=`<p class="error">${escape(error.message)}</p>`}}}
function save(){localStorage.setItem("gmi-dashboard",JSON.stringify(state.charts))}
function starterBoard(){return [{dataset:"gsc_live",dimension:"query",metric:"clicks",aggregation:"sum",chart:"kpi",limit:50,sort:"descending",filter:"",comparison:"previous_period",title:"Organic search clicks"},{dataset:"gsc_live",dimension:"date",metric:"impressions",aggregation:"sum",chart:"area",limit:50,sort:"ascending",filter:"",comparison:"previous_period",title:"Daily search impressions"},{dataset:"gsc_live",dimension:"country",metric:"clicks",aggregation:"sum",chart:"geo",limit:20,sort:"descending",filter:"",comparison:"previous_period",title:"Search clicks by country"},{dataset:"gsc_live",dimension:"device",metric:"ctr",aggregation:"average",chart:"table",limit:10,sort:"descending",filter:"",comparison:"previous_period",title:"Search performance by device"},{dataset:"ga4_live",dimension:"date",metric:"sessions",aggregation:"sum",chart:"line",limit:50,sort:"ascending",filter:"",comparison:"previous_period",title:"Daily website sessions"},{dataset:"ga4_live",dimension:"channel",metric:"sessions",aggregation:"sum",chart:"donut",limit:10,sort:"descending",filter:"",comparison:"previous_period",title:"Acquisition channel mix"},{dataset:"ga4_live",dimension:"landing_page",metric:"key_event_rate",aggregation:"average",chart:"horizontal_bar",limit:15,sort:"descending",filter:"",comparison:"previous_period",title:"Landing-page key-event rate"},{dataset:"ga4_live",dimension:"country",metric:"sessions",aggregation:"sum",chart:"geo",limit:20,sort:"descending",filter:"",comparison:"previous_period",title:"Sessions by country"}]}
async function init(){state.catalog=await fetch("/api/catalog").then(r=>r.json());options($("dataset"),Object.keys(state.catalog.datasets),key=>state.catalog.datasets[key].label);options($("chart"),state.catalog.chartTypes);syncDataset();const end=new Date(Date.now()-86400000),start=new Date(end.getTime()-27*86400000);$("end_date").value=end.toISOString().slice(0,10);$("start_date").value=start.toISOString().slice(0,10);const params=new URLSearchParams(location.search);if(params.has("board")){try{let encoded=params.get("board").replace(/-/g,"+").replace(/_/g,"/");while(encoded.length%4)encoded+="=";state.charts.push(...JSON.parse(atob(encoded)));$("board-title").textContent=params.get("board_title")||"Marketing evidence";save()}catch{}}else if(params.has("dataset")&&state.catalog.datasets[params.get("dataset")]){$("dataset").value=params.get("dataset");syncDataset();for(const id of ["dimension","metric","aggregation","chart","filter","limit","sort","title","start_date","end_date","comparison"])if(params.has(id))$(id).value=params.get(id);state.charts.push(spec());save()}if(location.search)history.replaceState({},"",location.pathname);$("dataset").onchange=syncDataset;$("add").onclick=()=>{state.charts.push(spec());save();render()};$("starter").onclick=()=>{state.charts.push(...starterBoard().map(item=>({...item,start_date:$("start_date").value,end_date:$("end_date").value})));save();render()};$("clear").onclick=()=>{state.charts=[];save();render()};render()}
init().catch(error=>{$("empty").innerHTML=`<strong>Dashboard unavailable</strong><span>${escape(error.message)}</span>`});
