const $=id=>document.getElementById(id),state={catalog:null,charts:JSON.parse(localStorage.getItem("gmi-dashboard")||"[]")},palette=["#176b4d","#3569d4","#ef7d42","#8b62b3","#c49a1a","#399d91"];
const fmt=value=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2,notation:Math.abs(value)>=100000?"compact":"standard"}).format(value),escape=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
function options(element,values,label=value=>value.replaceAll("_"," ")){element.innerHTML=values.map(value=>`<option value="${escape(value)}">${escape(label(value))}</option>`).join("")}
function syncDataset(){const item=state.catalog.datasets[$("dataset").value];options($("dimension"),item.dimensions);options($("metric"),item.metrics)}
function spec(){return {dataset:$("dataset").value,dimension:$("dimension").value,metric:$("metric").value,aggregation:$("aggregation").value,chart:$("chart").value,filter:$("filter").value,limit:Number($("limit").value),sort:$("sort").value,title:$("title").value}}
async function query(value){const response=await fetch("/api/query",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)}),result=await response.json();if(!response.ok)throw new Error(result.error);return result}
function chartHtml(type,points){if(!points.length)return '<p class="error">No evidence matched this view.</p>';const max=Math.max(...points.map(p=>Math.abs(p.value)),1);
 if(type==="kpi")return `<div class="kpi"><strong>${fmt(points.reduce((s,p)=>s+p.value,0))}</strong><span>Total across ${points.length} groups</span></div>`;
 if(type==="table")return `<table><thead><tr><th>Group</th><th>Value</th></tr></thead><tbody>${points.map(p=>`<tr><td>${escape(p.label)}</td><td>${fmt(p.value)}</td></tr>`).join("")}</tbody></table>`;
 if(type==="horizontal_bar")return `<div class="hbars">${points.map(p=>`<div class="hrow"><span title="${escape(p.label)}">${escape(p.label)}</span><div class="hbar" style="width:${Math.abs(p.value)/max*100}%"></div><b>${fmt(p.value)}</b></div>`).join("")}</div>`;
 if(type==="donut"){const total=points.reduce((s,p)=>s+Math.max(0,p.value),0)||1;let cursor=0;const stops=points.map((p,i)=>{const start=cursor;cursor+=Math.max(0,p.value)/total*100;return `${palette[i%palette.length]} ${start}% ${cursor}%`});return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops.join(",")})"></div><div class="legend">${points.slice(0,8).map((p,i)=>`<span><i style="background:${palette[i%palette.length]}"></i>${escape(p.label)} · ${fmt(p.value)}</span>`).join("")}</div></div>`}
 if(type==="line"||type==="area"){const width=600,height=210,coords=points.map((p,i)=>`${points.length===1?width/2:i/(points.length-1)*width},${height-Math.max(0,p.value)/max*(height-20)}`),fill=type==="area"?`<polygon points="0,${height} ${coords.join(" ")} ${width},${height}" fill="#176b4d" opacity=".14"/>`:"";return `<svg viewBox="0 0 ${width} ${height}" role="img">${fill}<polyline points="${coords.join(" ")}" fill="none" stroke="#176b4d" stroke-width="4"/>${coords.map((c,i)=>{const [x,y]=c.split(",");return `<circle cx="${x}" cy="${y}" r="4" fill="#ef7d42"><title>${escape(points[i].label)}: ${fmt(points[i].value)}</title></circle>`}).join("")}</svg>`}
 return `<div class="bars">${points.map(p=>`<div class="bar-wrap"><div class="bar" style="height:${Math.abs(p.value)/max*88}%"><em>${fmt(p.value)}</em></div><span title="${escape(p.label)}">${escape(p.label)}</span></div>`).join("")}</div>`}
async function render(){const grid=$("grid");grid.innerHTML="";$("empty").hidden=state.charts.length>0;$("count").textContent=`${state.charts.length} chart${state.charts.length===1?"":"s"}`;for(const [index,item] of state.charts.entries()){const node=$("card").content.cloneNode(true),article=node.querySelector("article");node.querySelector("h3").textContent=item.title||`${item.metric.replaceAll("_"," ")} by ${item.dimension.replaceAll("_"," ")}`;node.querySelector(".meta").textContent=`${state.catalog.datasets[item.dataset].label} · ${item.aggregation} · ${item.chart.replaceAll("_"," ")}`;node.querySelector(".remove").onclick=()=>{state.charts.splice(index,1);save();render()};grid.append(node);try{const result=await query(item);article.querySelector(".viz").innerHTML=chartHtml(item.chart,result.points);article.querySelector(".foot").textContent=`${result.summary.matchedRows} matched rows · calculated locally · ${new Date(result.generatedAt).toLocaleTimeString()}`}catch(error){article.querySelector(".viz").innerHTML=`<p class="error">${escape(error.message)}</p>`}}}
function save(){localStorage.setItem("gmi-dashboard",JSON.stringify(state.charts))}
async function init(){state.catalog=await fetch("/api/catalog").then(r=>r.json());options($("dataset"),Object.keys(state.catalog.datasets),key=>state.catalog.datasets[key].label);options($("chart"),state.catalog.chartTypes);syncDataset();const params=new URLSearchParams(location.search);if(params.has("dataset")&&state.catalog.datasets[params.get("dataset")]){$("dataset").value=params.get("dataset");syncDataset();for(const id of ["dimension","metric","aggregation","chart","filter","limit","sort","title"])if(params.has(id))$(id).value=params.get(id);state.charts.push(spec());save();history.replaceState({},"",location.pathname)}$("dataset").onchange=syncDataset;$("add").onclick=()=>{state.charts.push(spec());save();render()};$("clear").onclick=()=>{state.charts=[];save();render()};render()}
init().catch(error=>{$("empty").innerHTML=`<strong>Dashboard unavailable</strong><span>${escape(error.message)}</span>`});
