import {Pool} from "pg";
import type {EvidenceBundle} from "../evidence/schema.js";
import type {WarehouseScope} from "./types.js";

/** Hosted evidence repository. All reads and mutations require tenant and account predicates. */
export class PostgresEvidenceWarehouse{
 private pool:Pool;
 constructor(connectionString=process.env.WAREHOUSE_DATABASE_URL){if(!connectionString)throw new Error("WAREHOUSE_DATABASE_URL is required");this.pool=new Pool({connectionString,max:Number(process.env.WAREHOUSE_DB_POOL_SIZE??10),ssl:process.env.WAREHOUSE_DB_SSL==="disable"?false:{rejectUnauthorized:true}})}
 async migrate(){await this.pool.query(`CREATE TABLE IF NOT EXISTS evidence_snapshots(id text PRIMARY KEY,tenant_id text NOT NULL,account_id text NOT NULL,captured_at timestamptz NOT NULL,mapping_version integer NOT NULL,semantic_schema_version integer,metric_definitions_version text,content_hash text NOT NULL,payload jsonb NOT NULL,UNIQUE(tenant_id,account_id,content_hash)); CREATE INDEX IF NOT EXISTS evidence_snapshots_scope ON evidence_snapshots(tenant_id,account_id,captured_at); CREATE TABLE IF NOT EXISTS normalized_evidence(snapshot_id text NOT NULL REFERENCES evidence_snapshots(id) ON DELETE CASCADE,evidence_id text NOT NULL,tenant_id text NOT NULL,account_id text NOT NULL,source text NOT NULL,retrieved_at timestamptz NOT NULL,content_hash text NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(snapshot_id,evidence_id)); CREATE INDEX IF NOT EXISTS normalized_evidence_scope ON normalized_evidence(tenant_id,account_id,source,retrieved_at); CREATE TABLE IF NOT EXISTS raw_connector_records(id text PRIMARY KEY,snapshot_id text NOT NULL REFERENCES evidence_snapshots(id) ON DELETE CASCADE,tenant_id text NOT NULL,account_id text NOT NULL,source text NOT NULL,retrieved_at timestamptz NOT NULL,content_hash text NOT NULL,payload jsonb NOT NULL); CREATE TABLE IF NOT EXISTS evidence_lineage(snapshot_id text NOT NULL,evidence_id text NOT NULL,tenant_id text NOT NULL,account_id text NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(snapshot_id,evidence_id),FOREIGN KEY(snapshot_id,evidence_id) REFERENCES normalized_evidence(snapshot_id,evidence_id) ON DELETE CASCADE); CREATE TABLE IF NOT EXISTS record_evidence(kind text NOT NULL,record_id text NOT NULL,snapshot_id text NOT NULL REFERENCES evidence_snapshots(id) ON DELETE RESTRICT,tenant_id text NOT NULL,account_id text NOT NULL,linked_at timestamptz NOT NULL,PRIMARY KEY(kind,record_id,snapshot_id));`)}
 async saveBundle(bundle:EvidenceBundle,scope:WarehouseScope){const client=await this.pool.connect();try{await client.query("BEGIN");const hash=(await import("node:crypto")).createHash("sha256").update(JSON.stringify(bundle)).digest("hex"),id=`snap_${hash.slice(0,24)}`,snapshot={id,...scope,capturedAt:bundle.generatedAt,mappingVersion:bundle.mappingVersion,semanticSchemaVersion:bundle.semanticSchemaVersion??null,metricDefinitionsVersion:bundle.metricDefinitionsVersion??null,contentHash:hash,evidenceCount:bundle.evidence.length,warnings:bundle.warnings};await client.query("INSERT INTO evidence_snapshots VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING",[id,scope.tenantId,scope.accountId,bundle.generatedAt,bundle.mappingVersion,bundle.semanticSchemaVersion??null,bundle.metricDefinitionsVersion??null,hash,snapshot]);for(const row of bundle.evidence){const contentHash=(await import("node:crypto")).createHash("sha256").update(JSON.stringify(row)).digest("hex"),stored={...row,snapshotId:id,...scope,contentHash},lineage={snapshotId:id,evidenceId:row.id,source:row.source,sourceRecordId:row.id,retrievedAt:row.retrievedAt,mappingVersion:bundle.mappingVersion,semanticSchemaVersion:bundle.semanticSchemaVersion??null,metricDefinitionsVersion:bundle.metricDefinitionsVersion??null,calculationMethod:row.provenance.method,limitations:row.provenance.limitations};await client.query("INSERT INTO normalized_evidence VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING",[id,row.id,scope.tenantId,scope.accountId,row.source,row.retrievedAt,contentHash,stored]);await client.query("INSERT INTO evidence_lineage VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING",[id,row.id,scope.tenantId,scope.accountId,lineage])}await client.query("COMMIT");return snapshot}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
 async reconstructSnapshot(id:string,scope:WarehouseScope){const snapshot=await this.pool.query("SELECT payload FROM evidence_snapshots WHERE id=$1 AND tenant_id=$2 AND account_id=$3",[id,scope.tenantId,scope.accountId]);if(!snapshot.rowCount)throw new Error("Evidence snapshot not found in tenant/account scope");const evidence=await this.pool.query("SELECT payload FROM normalized_evidence WHERE snapshot_id=$1 AND tenant_id=$2 AND account_id=$3 ORDER BY evidence_id",[id,scope.tenantId,scope.accountId]),lineage=await this.pool.query("SELECT payload FROM evidence_lineage WHERE snapshot_id=$1 AND tenant_id=$2 AND account_id=$3 ORDER BY evidence_id",[id,scope.tenantId,scope.accountId]);return {snapshot:snapshot.rows[0].payload,evidence:evidence.rows.map(x=>x.payload),lineage:lineage.rows.map(x=>x.payload)}}
 async close(){await this.pool.end()}
}
