import Database from "better-sqlite3";
import {createHash} from "node:crypto";
import {mkdirSync} from "node:fs";
import {dirname} from "node:path";
import {runtimeStatePath} from "../runtime/paths.js";
import type {EvidenceBundle,NormalizedEvidence} from "../evidence/schema.js";
import {WAREHOUSE_SCHEMA_VERSION,type DecisionEvidenceLink,type EvidenceWarehouse,type RawConnectorRecord,type WarehouseEvidence,type WarehouseExport,type WarehouseLineage,type WarehouseRecordKind,type WarehouseRecordLink,type WarehouseScope,type WarehouseSnapshot} from "./types.js";

const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const safe=(value:string)=>{if(!/^[a-zA-Z0-9_.-]{1,100}$/.test(value))throw new Error("Warehouse tenant and account IDs must use letters, numbers, dot, underscore or hyphen");return value};
const parse=<T>(value:string)=>JSON.parse(value) as T;

export class SqliteEvidenceWarehouse implements EvidenceWarehouse{
 private db:Database.Database;
 constructor(path=process.env.MARKETING_WAREHOUSE_DB??runtimeStatePath("warehouse","evidence.sqlite")){mkdirSync(dirname(path),{recursive:true,mode:0o700});this.db=new Database(path);this.db.pragma("journal_mode = WAL");this.db.pragma("foreign_keys = ON");this.db.pragma("busy_timeout = 5000");this.db.exec(`CREATE TABLE IF NOT EXISTS warehouse_meta(version INTEGER NOT NULL); INSERT INTO warehouse_meta(version) SELECT 1 WHERE NOT EXISTS(SELECT 1 FROM warehouse_meta);
CREATE TABLE IF NOT EXISTS evidence_snapshots(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,captured_at TEXT NOT NULL,mapping_version INTEGER NOT NULL,semantic_schema_version INTEGER,metric_definitions_version TEXT,content_hash TEXT NOT NULL,payload TEXT NOT NULL,UNIQUE(tenant_id,account_id,content_hash));
CREATE INDEX IF NOT EXISTS evidence_snapshots_scope ON evidence_snapshots(tenant_id,account_id,captured_at);
CREATE TABLE IF NOT EXISTS normalized_evidence(snapshot_id TEXT NOT NULL,evidence_id TEXT NOT NULL,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,source TEXT NOT NULL,retrieved_at TEXT NOT NULL,content_hash TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(snapshot_id,evidence_id),FOREIGN KEY(snapshot_id) REFERENCES evidence_snapshots(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS normalized_evidence_scope ON normalized_evidence(tenant_id,account_id,source,retrieved_at);
CREATE TABLE IF NOT EXISTS raw_connector_records(id TEXT PRIMARY KEY,snapshot_id TEXT NOT NULL,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,source TEXT NOT NULL,retrieved_at TEXT NOT NULL,content_hash TEXT NOT NULL,payload TEXT NOT NULL,FOREIGN KEY(snapshot_id) REFERENCES evidence_snapshots(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS raw_connector_records_scope ON raw_connector_records(tenant_id,account_id,source,retrieved_at);
CREATE TABLE IF NOT EXISTS evidence_lineage(snapshot_id TEXT NOT NULL,evidence_id TEXT NOT NULL,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(snapshot_id,evidence_id),FOREIGN KEY(snapshot_id,evidence_id) REFERENCES normalized_evidence(snapshot_id,evidence_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS decision_evidence(decision_id TEXT NOT NULL,snapshot_id TEXT NOT NULL,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,linked_at TEXT NOT NULL,PRIMARY KEY(decision_id,snapshot_id),FOREIGN KEY(snapshot_id) REFERENCES evidence_snapshots(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS record_evidence(kind TEXT NOT NULL,record_id TEXT NOT NULL,snapshot_id TEXT NOT NULL,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,linked_at TEXT NOT NULL,PRIMARY KEY(kind,record_id,snapshot_id),FOREIGN KEY(snapshot_id) REFERENCES evidence_snapshots(id) ON DELETE RESTRICT);`)}
 saveBundle(bundle:EvidenceBundle,scope:WarehouseScope){const tenantId=safe(scope.tenantId),accountId=safe(scope.accountId),contentHash=hash(bundle),id=`snap_${contentHash.slice(0,24)}`,snapshot:WarehouseSnapshot={id,tenantId,accountId,capturedAt:bundle.generatedAt,mappingVersion:bundle.mappingVersion,semanticSchemaVersion:bundle.semanticSchemaVersion??null,metricDefinitionsVersion:bundle.metricDefinitionsVersion??null,contentHash,evidenceCount:bundle.evidence.length,warnings:bundle.warnings};const write=this.db.transaction(()=>{this.db.prepare("INSERT OR IGNORE INTO evidence_snapshots VALUES(?,?,?,?,?,?,?,?,?)").run(id,tenantId,accountId,bundle.generatedAt,bundle.mappingVersion,bundle.semanticSchemaVersion??null,bundle.metricDefinitionsVersion??null,contentHash,JSON.stringify(snapshot));const evidence=this.db.prepare("INSERT OR IGNORE INTO normalized_evidence VALUES(?,?,?,?,?,?,?,?)"),lineage=this.db.prepare("INSERT OR IGNORE INTO evidence_lineage VALUES(?,?,?,?,?)");for(const row of bundle.evidence){const stored:WarehouseEvidence={...row,snapshotId:id,tenantId,accountId,contentHash:hash(row)},trail:WarehouseLineage={snapshotId:id,evidenceId:row.id,source:row.source,sourceRecordId:row.id,retrievedAt:row.retrievedAt,mappingVersion:bundle.mappingVersion,semanticSchemaVersion:bundle.semanticSchemaVersion??null,metricDefinitionsVersion:bundle.metricDefinitionsVersion??null,calculationMethod:row.provenance.method,limitations:row.provenance.limitations};evidence.run(id,row.id,tenantId,accountId,row.source,row.retrievedAt,stored.contentHash,JSON.stringify(stored));lineage.run(id,row.id,tenantId,accountId,JSON.stringify(trail))}});write();return snapshot}
 saveRawRecords(snapshotId:string,source:string,records:unknown[],scope:WarehouseScope){this.getSnapshot(snapshotId,scope)??(()=>{throw new Error("Evidence snapshot not found in tenant/account scope")})();const tenantId=safe(scope.tenantId),accountId=safe(scope.accountId),statement=this.db.prepare("INSERT OR IGNORE INTO raw_connector_records VALUES(?,?,?,?,?,?,?,?)"),rows=records.map((payload,index)=>{const contentHash=hash(payload),row:RawConnectorRecord={id:`raw_${hash([snapshotId,source,index,contentHash]).slice(0,24)}`,snapshotId,tenantId,accountId,source,retrievedAt:new Date().toISOString(),contentHash,payload};statement.run(row.id,snapshotId,tenantId,accountId,source,row.retrievedAt,contentHash,JSON.stringify(payload));return row});return rows}
 getSnapshot(id:string,scope:WarehouseScope){const row=this.db.prepare("SELECT payload FROM evidence_snapshots WHERE id=? AND tenant_id=? AND account_id=?").get(id,safe(scope.tenantId),safe(scope.accountId)) as {payload:string}|undefined;return row?parse<WarehouseSnapshot>(row.payload):undefined}
 listSnapshots(scope:WarehouseScope,limit=100){return (this.db.prepare("SELECT payload FROM evidence_snapshots WHERE tenant_id=? AND account_id=? ORDER BY captured_at DESC LIMIT ?").all(safe(scope.tenantId),safe(scope.accountId),Math.min(1000,Math.max(1,limit))) as {payload:string}[]).map(row=>parse<WarehouseSnapshot>(row.payload))}
 reconstructSnapshot(id:string,scope:WarehouseScope){const snapshot=this.getSnapshot(id,scope);if(!snapshot)throw new Error("Evidence snapshot not found in tenant/account scope");const args=[id,safe(scope.tenantId),safe(scope.accountId)],evidence=(this.db.prepare("SELECT payload FROM normalized_evidence WHERE snapshot_id=? AND tenant_id=? AND account_id=? ORDER BY evidence_id").all(...args) as {payload:string}[]).map(x=>parse<WarehouseEvidence>(x.payload)),lineage=(this.db.prepare("SELECT payload FROM evidence_lineage WHERE snapshot_id=? AND tenant_id=? AND account_id=? ORDER BY evidence_id").all(...args) as {payload:string}[]).map(x=>parse<WarehouseLineage>(x.payload));return {snapshot,evidence,lineage}}
 linkRecord(kind:WarehouseRecordKind,recordId:string,snapshotId:string,scope:WarehouseScope){this.getSnapshot(snapshotId,scope)??(()=>{throw new Error("Evidence snapshot not found in tenant/account scope")})();const row:WarehouseRecordLink={kind,recordId,snapshotId,tenantId:safe(scope.tenantId),accountId:safe(scope.accountId),linkedAt:new Date().toISOString()};this.db.prepare("INSERT OR IGNORE INTO record_evidence VALUES(?,?,?,?,?,?)").run(kind,recordId,snapshotId,row.tenantId,row.accountId,row.linkedAt);return row}
 linkDecision(decisionId:string,snapshotId:string,scope:WarehouseScope){const row=this.linkRecord("decision",decisionId,snapshotId,scope);return {decisionId,snapshotId,tenantId:row.tenantId,accountId:row.accountId,linkedAt:row.linkedAt}}
 reconstructDecision(decisionId:string,scope:WarehouseScope){const links=(this.db.prepare("SELECT record_id as decisionId,snapshot_id as snapshotId,tenant_id as tenantId,account_id as accountId,linked_at as linkedAt FROM record_evidence WHERE kind='decision' AND record_id=? AND tenant_id=? AND account_id=? ORDER BY linked_at").all(decisionId,safe(scope.tenantId),safe(scope.accountId)) as DecisionEvidenceLink[]);return links.map(link=>({link,...this.reconstructSnapshot(link.snapshotId,scope)}))}
 exportScope(scope:WarehouseScope):WarehouseExport{const tenant=safe(scope.tenantId),account=safe(scope.accountId),snapshots=this.listSnapshots(scope,1000),expanded=snapshots.map(x=>this.reconstructSnapshot(x.id,scope)),rawRecords=(this.db.prepare("SELECT payload,id,snapshot_id as snapshotId,tenant_id as tenantId,account_id as accountId,source,retrieved_at as retrievedAt,content_hash as contentHash FROM raw_connector_records WHERE tenant_id=? AND account_id=?").all(tenant,account) as (Omit<RawConnectorRecord,"payload">&{payload:string})[]).map(x=>({...x,payload:parse(x.payload)})),recordLinks=this.db.prepare("SELECT kind,record_id as recordId,snapshot_id as snapshotId,tenant_id as tenantId,account_id as accountId,linked_at as linkedAt FROM record_evidence WHERE tenant_id=? AND account_id=?").all(tenant,account) as WarehouseRecordLink[];return {schemaVersion:WAREHOUSE_SCHEMA_VERSION,exportedAt:new Date().toISOString(),scope:{tenantId:tenant,accountId:account},snapshots,rawRecords,evidence:expanded.flatMap(x=>x.evidence),lineage:expanded.flatMap(x=>x.lineage),recordLinks}}
 deleteScope(scope:WarehouseScope){const tenant=safe(scope.tenantId),account=safe(scope.accountId),count=(table:string)=>Number((this.db.prepare(`SELECT COUNT(*) as count FROM ${table} WHERE tenant_id=? AND account_id=?`).get(tenant,account) as {count:number}).count),result={snapshots:count("evidence_snapshots"),rawRecords:count("raw_connector_records"),evidence:count("normalized_evidence"),lineage:count("evidence_lineage"),recordLinks:count("record_evidence")};this.db.transaction(()=>{this.db.prepare("DELETE FROM record_evidence WHERE tenant_id=? AND account_id=?").run(tenant,account);this.db.prepare("DELETE FROM decision_evidence WHERE tenant_id=? AND account_id=?").run(tenant,account);this.db.prepare("DELETE FROM evidence_snapshots WHERE tenant_id=? AND account_id=?").run(tenant,account)})();return result}
 applyRetention(scope:WarehouseScope,before:string){if(!Number.isFinite(Date.parse(before)))throw new Error("Retention cutoff must be an ISO date");const result=this.db.prepare("DELETE FROM evidence_snapshots WHERE tenant_id=? AND account_id=? AND captured_at<? AND id NOT IN(SELECT snapshot_id FROM record_evidence WHERE tenant_id=? AND account_id=?)").run(safe(scope.tenantId),safe(scope.accountId),before,safe(scope.tenantId),safe(scope.accountId));return {snapshots:result.changes}}
 close(){this.db.close()}
}
