import {readFileSync,readdirSync} from "node:fs";
import {dirname,join} from "node:path";
import {fileURLToPath} from "node:url";
import type {MarketingCase,RetrievedCase,TransferabilityContext} from "./types.js";
import {canonicalizeCase} from "./ontology.js";
export {approvedCaseSchema as marketingCaseSchema} from "./ontology.js";
const root=join(dirname(fileURLToPath(import.meta.url)),"../..");
const tokenize=(value:string)=>new Set(value.toLowerCase().match(/[a-z0-9]{3,}/g)??[]);
const overlap=(left:string,right:string)=>{const a=tokenize(left),b=tokenize(right);if(!a.size||!b.size)return .5;const common=[...a].filter(x=>b.has(x)).length;return common/Math.sqrt(a.size*b.size)};
const fit=(wanted:string|undefined,actual:string)=>wanted?Math.min(1,overlap(wanted,actual)*2):.5;
const quality={A:1,B:.9,C:.75,D:.55,E:.3};
/** Weights sum to 1. Semantic and objective fit dominate; structural GTM/customer/business fit collectively matters more than wording. Evidence is a bounded quality modifier, while explicit non-transfer matches are a separate penalty. */
export const transferabilityWeights={semanticSimilarity:.2,industryFit:.08,businessModelFit:.11,gtmFit:.1,customerFit:.1,objectiveFit:.16,geographyFit:.06,marketMaturityFit:.05,evidenceQuality:.1,failureRelevance:.04} as const;
const infer=(query:string):TransferabilityContext=>({objective:query,businessModel:/b2b|enterprise|saas/i.test(query)?"B2B SaaS":/ecommerce|consumer|retail/i.test(query)?"consumer ecommerce":undefined,gtmMotion:/product.?led|plg/i.test(query)?"product-led":/sales|enterprise/i.test(query)?"sales-led":undefined,customerType:/enterprise|b2b/i.test(query)?"business":/consumer|b2c/i.test(query)?"consumer":undefined,geography:/india/i.test(query)?"India":/apac|asia/i.test(query)?"APAC":undefined,includeFailureCases:/risk|fail|crisis|decline|stop/i.test(query)});
export function loadKnowledgeBase(directory=process.env.MARKETING_KNOWLEDGE_DIR||join(root,"knowledge/cases")):MarketingCase[]{
 const seen=new Set<string>(); return readdirSync(directory).filter(x=>x.endsWith(".json")).sort().map(file=>canonicalizeCase(JSON.parse(readFileSync(join(directory,file),"utf8")))).filter(row=>{if(seen.has(row.id))throw new Error(`Duplicate marketing case id: ${row.id}`);seen.add(row.id);return true});
}
export function retrievePrecedents(query:string,limit=5,cases=loadKnowledgeBase(),provided:TransferabilityContext={}):RetrievedCase[]{
 const context={...infer(query),...provided},terms=tokenize(query);
 return cases.map(row=>{const searchableText=[row.campaign,row.brand,row.objective,row.businessContext,row.strategy,...row.disciplines,...row.audience,...row.failureModes,...row.transferConditions].join(" "),searchable=tokenize(searchableText),matched=[...terms].filter(x=>searchable.has(x)),nonTransferText=row.nonTransferConditions.join(" "),penalty=Math.min(.35,overlap(query,nonTransferText)*.5),components={semanticSimilarity:Math.min(1,overlap(query,searchableText)*2),industryFit:fit(context.industry,row.category),businessModelFit:fit(context.businessModel,row.businessModel),gtmFit:fit(context.gtmMotion,`${row.businessModel} ${row.disciplines.join(" ")} ${row.strategy}`),customerFit:fit(context.customerType,row.audience.join(" ")),objectiveFit:fit(context.objective,row.objective),geographyFit:context.geography?Math.max(...row.markets.map(x=>fit(context.geography,x))):.5,marketMaturityFit:fit(context.marketMaturity,row.marketMaturity),evidenceQuality:quality[row.evidenceGrade],failureRelevance:context.includeFailureCases?(row.outcome!=="succeeded"?1:0):.5,nonTransferPenalty:penalty},weighted=Object.entries(transferabilityWeights).reduce((sum,[key,weight])=>sum+components[key as keyof typeof transferabilityWeights]*weight,0),score=Math.max(0,Math.min(100,Math.round((weighted-penalty)*100))),similarities=Object.entries(components).filter(([key,value])=>key!=="nonTransferPenalty"&&value>=.7).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([key])=>key),differences=Object.entries(components).filter(([key,value])=>key!=="nonTransferPenalty"&&value<.35).map(([key])=>key);return {case:row,score,matchedTerms:matched,components,strongestSimilarities:similarities,materialDifferences:differences,transferRisks:[...row.nonTransferConditions,...(penalty>.1?["Query overlaps an explicit non-transfer condition"]:[])],whyIncluded:`Transferability ${score}/100; strongest fit: ${similarities.join(", ")||"limited evidence fit"}.`,whyMayNotTransfer:`Material differences: ${differences.join(", ")||"none detected from available fields"}. ${row.nonTransferConditions.join(" ")}`}}).filter(x=>x.score>5).sort((a,b)=>b.score-a.score||a.case.id.localeCompare(b.case.id)).slice(0,limit);
}
export function renderPrecedents(rows:RetrievedCase[]){return rows.length?rows.map(row=>{const c=row.case;return `- [${c.id}] ${c.brand}, ${c.campaign} — transferability=${row.score}/100; components=${JSON.stringify(row.components)}; strongest similarities=${row.strongestSimilarities.join(", ")||"none"}; material differences=${row.materialDifferences.join(", ")||"none"}; evidence=${c.evidenceGrade}/${c.causalConfidence}; included because: ${row.whyIncluded}; may not transfer because: ${row.whyMayNotTransfer}; risks=${row.transferRisks.join("; ")}; sources=${c.sources.map(s=>s.url).join(", ")}`}).join("\n"):"- No sufficiently relevant precedent found. State that limitation; do not invent one."}
