import {createHash} from "node:crypto";
import {z} from "zod";
import type {EvidenceGrade,MarketingCase} from "./types.js";
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const source=z.object({id:z.string().regex(/^[a-z0-9-]+$/).optional(),title:z.string().min(1),url:z.string().url(),publisher:z.string().min(1),accessedAt:date,sourceType:z.enum(["independent-research","regulatory","company-report","platform-library","award-case","journalism","commentary"]).optional(),methodology:z.string().optional()});
const measurement=z.object({name:z.string().min(1),level:z.enum(["business","brand","behavior","media","reputation"]),direction:z.enum(["positive","negative","neutral","unknown"]),value:z.number().optional(),unit:z.string().min(1).optional(),incrementality:z.enum(["experimental","econometric","observational","claimed","unknown"]),sourceIds:z.array(z.string())});
const rights=z.object({basis:z.enum(["public-domain","permission-granted","licensed-redistribution","factual-metadata-only","restricted","unknown"]),redistributionAllowed:z.boolean(),reviewedBy:z.string().min(2),reviewedAt:date,notes:z.string()});
const review=z.object({status:z.literal("approved"),reviewedBy:z.string().min(2),reviewedAt:date,notes:z.string()});
const common={id:z.string().regex(/^[a-z0-9-]+$/),campaign:z.string().min(1),brand:z.string().min(1),period:z.string().min(1),markets:z.array(z.string()).min(1),disciplines:z.array(z.string()).min(1),objective:z.string().min(1),audience:z.array(z.string()).min(1),businessContext:z.string().min(1),strategy:z.string().min(1),execution:z.array(z.string()).min(1),outcome:z.enum(["succeeded","failed","mixed"]),outcomes:z.array(z.string()).min(1),evidenceQuality:z.enum(["low","medium","high"]),causalConfidence:z.enum(["low","medium","high"]),whatWorked:z.array(z.string()),whatFailed:z.array(z.string()),failureModes:z.array(z.string()),transferConditions:z.array(z.string()).min(1),nonTransferConditions:z.array(z.string()).min(1),sources:z.array(source).min(1)};
export const legacyCaseSchema=z.object(common).strict();
export const contributionSchema=z.object({schemaVersion:z.literal(2),...common,category:z.string().min(1),businessModel:z.string().min(1),marketMaturity:z.string().min(1),economicContext:z.string().min(1),evidenceGrade:z.enum(["A","B","C","D","E"]),outcomeMeasurements:z.array(measurement),rights,review:z.object({status:z.enum(["pending","changes-requested"]),submittedBy:z.string().min(2),submittedAt:date,notes:z.string()})}).strict();
export const approvedCaseSchema=contributionSchema.omit({review:true}).extend({review}).strict();
const gradeMap:Record<string,EvidenceGrade>={high:"D",medium:"D",low:"D"};
export function canonicalizeCase(value:unknown):MarketingCase{const v2=approvedCaseSchema.safeParse(value);if(v2.success)return v2.data as MarketingCase;const old=legacyCaseSchema.parse(value);return {...old,schemaVersion:2,category:"unclassified",businessModel:"unclassified",marketMaturity:"unclassified",economicContext:"not recorded",evidenceGrade:gradeMap[old.evidenceQuality],outcomeMeasurements:[],rights:{basis:"factual-metadata-only",redistributionAllowed:true,reviewedBy:"v1 migration",reviewedAt:"2026-09-11",notes:"Independently written factual metadata with outbound source links; source content is not redistributed."},review:{status:"approved",reviewedBy:"v1 migration",reviewedAt:"2026-09-11",notes:"Canonicalized from v1; ontology enrichment remains required."}} as MarketingCase}
const normalized=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
export function caseFingerprint(row:Pick<MarketingCase,"brand"|"campaign"|"period">){return createHash("sha256").update(`${normalized(row.brand)}|${normalized(row.campaign)}|${normalized(row.period)}`).digest("hex")}
export function evidenceGradeIsConsistent(row:MarketingCase){const rank={A:5,B:4,C:3,D:2,E:1};const strongest:EvidenceGrade=row.outcomeMeasurements.some(x=>x.incrementality==="experimental")?"A":row.outcomeMeasurements.some(x=>x.incrementality==="econometric")?"B":row.sources.some(x=>x.sourceType==="independent-research"||x.sourceType==="regulatory")?"B":row.sources.some(x=>x.sourceType==="company-report"||x.sourceType==="award-case")?"C":"D";return {declared:row.evidenceGrade,maximumSupported:strongest,consistent:rank[row.evidenceGrade]<=rank[strongest]}}
