import {appendFileSync,chmodSync,existsSync,mkdirSync,readFileSync,readdirSync,renameSync,writeFileSync} from "node:fs";
import {basename,dirname,join,resolve} from "node:path";
import {contributionSchema,approvedCaseSchema,canonicalizeCase,caseFingerprint,evidenceGradeIsConsistent} from "./ontology.js";
import {loadKnowledgeBase} from "./knowledge.js";
import type {MarketingCase} from "./types.js";
const root=()=>process.cwd(),queue=()=>process.env.MARKETING_REVIEW_QUEUE||join(root(),".marketing-corpus/review-queue"),audit=()=>join(root(),".marketing-corpus/review-audit.jsonl");
const tokens=(x:string)=>new Set(x.toLowerCase().match(/[a-z0-9]{3,}/g)??[]);
const similarity=(a:string,b:string)=>{const aa=tokens(a),bb=tokens(b),intersection=[...aa].filter(x=>bb.has(x)).length,union=new Set([...aa,...bb]).size;return union?intersection/union:0};
const descriptor=(x:{brand:string;campaign:string;period:string})=>`${x.brand} ${x.campaign} ${x.period}`;
const event=(value:unknown)=>{mkdirSync(dirname(audit()),{recursive:true,mode:0o700});appendFileSync(audit(),`${JSON.stringify(value)}\n`,{mode:0o600});chmodSync(audit(),0o600)};
export function duplicateCandidates(value:unknown,existing=loadKnowledgeBase()){const candidate=contributionSchema.parse(value),fingerprint=caseFingerprint(candidate);return existing.map(row=>({id:row.id,exact:caseFingerprint(row)===fingerprint,similarity:similarity(descriptor(candidate),descriptor(row))})).filter(x=>x.exact||x.similarity>=.6).sort((a,b)=>Number(b.exact)-Number(a.exact)||b.similarity-a.similarity)}
export function submitContribution(path:string){const source=resolve(path),candidate=contributionSchema.parse(JSON.parse(readFileSync(source,"utf8"))),duplicates=duplicateCandidates(candidate);if(duplicates.some(x=>x.exact))throw new Error(`Exact duplicate: ${duplicates.filter(x=>x.exact).map(x=>x.id).join(", ")}`);mkdirSync(queue(),{recursive:true,mode:0o700});const target=join(queue(),`${candidate.id}.json`);writeFileSync(target,`${JSON.stringify(candidate,null,2)}\n`,{flag:"wx",mode:0o600});event({at:new Date().toISOString(),action:"submitted",id:candidate.id,source:basename(source),possibleDuplicates:duplicates});return {candidate,target,duplicates}}
export function listContributions(){if(!existsSync(queue()))return [];return readdirSync(queue()).filter(x=>x.endsWith(".json")).sort().map(file=>contributionSchema.parse(JSON.parse(readFileSync(join(queue(),file),"utf8"))))}
const checkedId=(id:string)=>{if(!/^[a-z0-9-]+$/.test(id))throw new Error("Invalid contribution id");return id};
export function approveContribution(id:string,reviewer:string,notes:string){const safe=checkedId(id),path=join(queue(),`${safe}.json`),candidate=contributionSchema.parse(JSON.parse(readFileSync(path,"utf8")));if(candidate.rights.basis==="restricted"||candidate.rights.basis==="unknown"||!candidate.rights.redistributionAllowed)throw new Error("Rights review does not permit public redistribution");const row=approvedCaseSchema.parse({...candidate,review:{status:"approved",reviewedBy:reviewer,reviewedAt:new Date().toISOString().slice(0,10),notes}});const grade=evidenceGradeIsConsistent(row as MarketingCase);if(!grade.consistent)throw new Error(`Evidence grade ${grade.declared} exceeds supported ${grade.maximumSupported}`);const target=join(root(),"knowledge/cases",`${safe}.json`);writeFileSync(target,`${JSON.stringify(row,null,2)}\n`,{flag:"wx"});renameSync(path,`${path}.approved`);event({at:new Date().toISOString(),action:"approved",id:safe,reviewer,notes});return {row,target}}
export function requestChanges(id:string,reviewer:string,notes:string){const safe=checkedId(id),path=join(queue(),`${safe}.json`),candidate=contributionSchema.parse(JSON.parse(readFileSync(path,"utf8")));writeFileSync(path,`${JSON.stringify({...candidate,review:{...candidate.review,status:"changes-requested",notes}},null,2)}\n`,{mode:0o600});event({at:new Date().toISOString(),action:"changes-requested",id:safe,reviewer,notes})}
