import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { lookup } from "node:dns/promises";
import { z } from "zod";
import { completedDateWindow } from "../google/dates.js";
import { renderCrm, summarizeCrm, type CrmFunnelRow, type CrmReport } from "./types.js";
const schema=z.object({version:z.literal(1),endpoint:z.string().url(),records_path:z.string().default("data"),token_env:z.string().regex(/^[A-Z][A-Z0-9_]+$/),authorization:z.enum(["bearer","x-api-key"]).default("bearer"),record_type:z.enum(["lead","contact","opportunity"]).default("opportunity"),fields:z.object({id:z.string(),created_date:z.string(),lifecycle_stage:z.string().optional(),opportunity_stage:z.string().optional(),campaign:z.string().optional(),first_touch_source:z.string().optional(),latest_touch_source:z.string().optional(),segment:z.string().optional(),pipeline_value:z.string().optional(),closed_won_revenue:z.string().optional(),status:z.string().optional()}),won_values:z.array(z.string()).default(["won","closed won","closed_won"])});
type Config=z.infer<typeof schema>;
const get=(value:unknown,path:string|undefined)=>path?path.split(".").reduce<unknown>((current,key)=>current&&typeof current==="object"?(current as Record<string,unknown>)[key]:undefined,value):undefined;
const privateAddress=(address:string)=>/^(127\.|10\.|192\.168\.|169\.254\.|0\.)/.test(address)||/^172\.(1[6-9]|2\d|3[01])\./.test(address)||address==="::1"||address==="::"||/^f[cd]/i.test(address)||/^fe[89ab]/i.test(address);
const safeEndpoint=async(value:string)=>{const url=new URL(value);if(url.protocol!=="https:")throw new Error("Generic CRM API endpoint must use HTTPS");const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".local"))throw new Error("Generic CRM API endpoint cannot target a private or loopback host");const addresses=await lookup(host,{all:true});if(!addresses.length||addresses.some(item=>privateAddress(item.address)))throw new Error("Generic CRM API endpoint resolved to a private or loopback address");return url};
export async function genericCrmApiReport(input:{startDate?:string;endDate?:string;rowLimit?:number;configPath?:string}={}):Promise<CrmReport>{
 const configured=input.configPath??process.env.GENERIC_CRM_API_CONFIG;if(!configured)throw new Error("GENERIC_CRM_API_CONFIG is not configured");
 const path=resolve(configured),config:Config=schema.parse(JSON.parse(readFileSync(path,"utf8"))),token=process.env[config.token_env];if(!token)throw new Error(`Generic CRM API token environment variable ${config.token_env} is not configured`);
 const endpoint=await safeEndpoint(config.endpoint),headers:Record<string,string>=config.authorization==="bearer"?{authorization:`Bearer ${token}`,accept:"application/json"}:{"x-api-key":token,accept:"application/json"},response=await fetch(endpoint,{headers,signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`Generic CRM API returned ${response.status}: ${(await response.text()).slice(0,250)}`);
 const body=await response.json(),records=get(body,config.records_path);if(!Array.isArray(records))throw new Error(`records_path '${config.records_path}' did not resolve to an array`);
 const dates=completedDateWindow(input.startDate,input.endDate),won=new Set(config.won_values.map(value=>value.toLowerCase())),normalized:CrmFunnelRow[]=records.map((record,index)=>{const field=(fieldPath:string|undefined)=>String(get(record,fieldPath)??""),amount=(fieldPath:string|undefined)=>Number(get(record,fieldPath)??0),status=field(config.fields.status),isWon=won.has(status.toLowerCase());return {source:"generic_crm_api",recordType:config.record_type,recordId:field(config.fields.id)||String(index+1),createdDate:field(config.fields.created_date),lifecycleStage:field(config.fields.lifecycle_stage),opportunityStage:field(config.fields.opportunity_stage)||status,campaign:field(config.fields.campaign),firstTouchSource:field(config.fields.first_touch_source),latestTouchSource:field(config.fields.latest_touch_source),segment:field(config.fields.segment)||"Unmapped",pipelineValue:isWon?0:amount(config.fields.pipeline_value),closedWonRevenue:isWon?amount(config.fields.closed_won_revenue)||amount(config.fields.pipeline_value):0,isWon}}),eligible=normalized.filter(row=>!/^\d{4}-\d{2}-\d{2}/.test(row.createdDate)||(row.createdDate.slice(0,10)>=dates.startDate&&row.createdDate.slice(0,10)<=dates.endDate)),rows=eligible.slice(0,Math.min(10000,Math.max(1,input.rowLimit??500))),summary=summarizeCrm(rows),warnings=["Field mappings and lifecycle definitions are operator-controlled and must be validated.","The adapter performs one HTTPS GET request only; pagination and associations are endpoint-specific.","Credential values come from a named environment variable and are never stored in the mapping file."];
 return {meta:{source:"generic_crm_api",startDate:dates.startDate,endDate:dates.endDate,retrievedAt:new Date().toISOString(),rowCount:rows.length,partial:eligible.length>rows.length,readOnly:true,warnings},rows,summary,markdown:renderCrm("Generic CRM API",dates.startDate,dates.endDate,rows,summary,warnings)};
}
