import { completedDateWindow } from "../google/dates.js";
import { fetchJson } from "./http.js";
import { renderCrm, summarizeCrm, type CrmFunnelRow, type CrmReport } from "./types.js";
type HubSpotObject={id:string;properties:Record<string,string|null>};
async function allObjects(object:string,properties:string[],rowLimit:number):Promise<{rows:HubSpotObject[];partial:boolean}>{const rows:HubSpotObject[]=[];let after:string|undefined;while(rows.length<rowLimit){const params=new URLSearchParams({limit:String(Math.min(100,rowLimit-rows.length)),properties:properties.join(",")});if(after)params.set("after",after);const page=await fetchJson(`https://api.hubapi.com/crm/v3/objects/${object}?${params}`,{headers:{authorization:`Bearer ${process.env.HUBSPOT_ACCESS_TOKEN}`}});rows.push(...(page.results??[]));after=page.paging?.next?.after;if(!after)break}return {rows,partial:Boolean(after)}}
export async function hubspotFunnelReport(input:{startDate?:string;endDate?:string;rowLimit?:number}):Promise<CrmReport>{
 if(!process.env.HUBSPOT_ACCESS_TOKEN)throw new Error("HUBSPOT_ACCESS_TOKEN is not configured");const dates=completedDateWindow(input.startDate,input.endDate),rowLimit=Math.min(10000,Math.max(1,input.rowLimit??1000)),contactProps=["createdate","lifecyclestage","hs_analytics_source","hs_analytics_source_data_1","hs_analytics_source_data_2"],dealProps=["createdate","dealstage","amount","closed_won_reason","closedate","pipeline","hs_is_closed_won","hs_analytics_source"];
 const [contacts,deals]=await Promise.all([allObjects("contacts",contactProps,rowLimit),allObjects("deals",dealProps,rowLimit)]),inRange=(date:string|null|undefined)=>Boolean(date&&date.slice(0,10)>=dates.startDate&&date.slice(0,10)<=dates.endDate),rows:CrmFunnelRow[]=[];
 for(const item of contacts.rows){const p=item.properties;if(inRange(p.createdate))rows.push({source:"hubspot",recordType:"contact",recordId:item.id,createdDate:p.createdate??"",lifecycleStage:p.lifecyclestage??"",opportunityStage:"",campaign:p.hs_analytics_source_data_1??"",firstTouchSource:p.hs_analytics_source??"",latestTouchSource:p.hs_analytics_source_data_2??"",segment:"Unmapped",pipelineValue:0,closedWonRevenue:0,isWon:false})}
 for(const item of deals.rows){const p=item.properties;if(inRange(p.createdate)){const amount=Number(p.amount??0),isWon=p.hs_is_closed_won==="true";rows.push({source:"hubspot",recordType:"opportunity",recordId:item.id,createdDate:p.createdate??"",lifecycleStage:"",opportunityStage:p.dealstage??"",campaign:p.hs_analytics_source??"",firstTouchSource:p.hs_analytics_source??"",latestTouchSource:p.hs_analytics_source??"",segment:p.pipeline??"Unmapped",pipelineValue:isWon?0:amount,closedWonRevenue:isWon?amount:0,isWon})}}
 const summary=summarizeCrm(rows),warnings=["HubSpot lifecycle and deal-stage definitions are portal-specific; verify them before comparing MQL, SQL, pipeline or revenue.","The connector reads CRM objects and never writes or updates them."];return {meta:{source:"hubspot",startDate:dates.startDate,endDate:dates.endDate,retrievedAt:new Date().toISOString(),rowCount:rows.length,partial:contacts.partial||deals.partial,readOnly:true,warnings},rows,summary,markdown:renderCrm("HubSpot",dates.startDate,dates.endDate,rows,summary,warnings)};
}
