import { completedDateWindow } from "../google/dates.js";
import { fetchJson } from "./http.js";
import { renderCrm, summarizeCrm, type CrmFunnelRow, type CrmReport } from "./types.js";
const query=async(soql:string)=>fetchJson(`${process.env.SALESFORCE_INSTANCE_URL}/services/data/v62.0/query?q=${encodeURIComponent(soql)}`,{headers:{authorization:`Bearer ${process.env.SALESFORCE_ACCESS_TOKEN}`}});
export async function salesforceFunnelReport(input:{startDate?:string;endDate?:string;rowLimit?:number}):Promise<CrmReport>{
 if(!process.env.SALESFORCE_INSTANCE_URL||!/^https:\/\/[A-Za-z0-9.-]+$/.test(process.env.SALESFORCE_INSTANCE_URL))throw new Error("SALESFORCE_INSTANCE_URL must be a valid HTTPS origin");if(!process.env.SALESFORCE_ACCESS_TOKEN)throw new Error("SALESFORCE_ACCESS_TOKEN is not configured");const dates=completedDateWindow(input.startDate,input.endDate),rowLimit=Math.min(2000,Math.max(1,input.rowLimit??1000)),start=`${dates.startDate}T00:00:00Z`,end=`${dates.endDate}T23:59:59Z`;
 const [leadResult,opportunityResult]=await Promise.all([query(`SELECT Id, Status, LeadSource, CreatedDate, ConvertedDate FROM Lead WHERE CreatedDate >= ${start} AND CreatedDate <= ${end} LIMIT ${rowLimit}`),query(`SELECT Id, StageName, Amount, IsWon, LeadSource, CampaignId, CreatedDate, CloseDate FROM Opportunity WHERE CreatedDate >= ${start} AND CreatedDate <= ${end} LIMIT ${rowLimit}`)]),rows:CrmFunnelRow[]=[];
 for(const item of leadResult.records??[])rows.push({source:"salesforce",recordType:"lead",recordId:item.Id,createdDate:item.CreatedDate??"",lifecycleStage:item.Status??"",opportunityStage:"",campaign:"",firstTouchSource:item.LeadSource??"",latestTouchSource:item.LeadSource??"",segment:"Unmapped",pipelineValue:0,closedWonRevenue:0,isWon:false});for(const item of opportunityResult.records??[]){const amount=Number(item.Amount??0);rows.push({source:"salesforce",recordType:"opportunity",recordId:item.Id,createdDate:item.CreatedDate??"",lifecycleStage:"",opportunityStage:item.StageName??"",campaign:item.CampaignId??"",firstTouchSource:item.LeadSource??"",latestTouchSource:item.LeadSource??"",segment:"Unmapped",pipelineValue:item.IsWon?0:amount,closedWonRevenue:item.IsWon?amount:0,isWon:Boolean(item.IsWon)})}
 const summary=summarizeCrm(rows),partial=Boolean(leadResult.nextRecordsUrl||opportunityResult.nextRecordsUrl),warnings=["Salesforce stage names and MQL/SQL definitions are organization-specific and require field mapping for authoritative funnel reporting.","The connector uses SOQL reads only and contains no mutation operations."];return {meta:{source:"salesforce",startDate:dates.startDate,endDate:dates.endDate,retrievedAt:new Date().toISOString(),rowCount:rows.length,partial,readOnly:true,warnings},rows,summary,markdown:renderCrm("Salesforce",dates.startDate,dates.endDate,rows,summary,warnings)};
}
