import { BetaAnalyticsDataClient } from "@google-analytics/data";
import { completedDateWindow } from "./dates.js";
export async function ga4AcquisitionReport(input:{days?:number;rowLimit?:number}):Promise<string>{
 const propertyId=process.env.GA4_PROPERTY_ID;if(!propertyId)throw new Error("GA4_PROPERTY_ID is not configured");if(!process.env.GOOGLE_APPLICATION_CREDENTIALS)throw new Error("GOOGLE_APPLICATION_CREDENTIALS is not configured");
 const days=Math.min(365,Math.max(1,input.days??28)),rowLimit=Math.min(10000,Math.max(1,input.rowLimit??50)),dates=completedDateWindow(undefined,undefined,days),client=new BetaAnalyticsDataClient();
 const [response]=await client.runReport({property:`properties/${propertyId}`,dateRanges:[{startDate:dates.startDate,endDate:dates.endDate}],dimensions:[{name:"sessionSourceMedium"},{name:"sessionCampaignName"},{name:"landingPagePlusQueryString"}],metrics:[{name:"sessions"},{name:"totalUsers"},{name:"keyEvents"},{name:"totalRevenue"}],orderBys:[{metric:{metricName:"sessions"},desc:true}],limit:rowLimit});
 const rows=(response.rows??[]).map(row=>{const dimensions=row.dimensionValues??[],metrics=row.metricValues??[],sessions=Number(metrics[0]?.value??0),keyEvents=Number(metrics[2]?.value??0);return {source:dimensions[0]?.value??"",campaign:dimensions[1]?.value??"",landingPage:dimensions[2]?.value??"",sessions,users:Number(metrics[1]?.value??0),keyEvents,revenue:Number(metrics[3]?.value??0),keyEventsPerSession:sessions?keyEvents/sessions:0}});
 return `# GA4 Acquisition & Landing Page Report\n\n**Property:** ${propertyId}  \n**Period:** ${dates.startDate} → ${dates.endDate}  \n**Rows:** ${rows.length}\n\n| Source / medium | Campaign | Landing page | Sessions | Users | Key events | Key events / session | Revenue |\n|---|---|---|---:|---:|---:|---:|---:|\n${rows.map(row=>`| ${row.source.replaceAll("|","\\|")} | ${row.campaign.replaceAll("|","\\|")} | ${row.landingPage.replaceAll("|","\\|")} | ${row.sessions} | ${row.users} | ${row.keyEvents} | ${row.keyEventsPerSession.toFixed(2)} | ${row.revenue.toFixed(2)} |`).join("\n")}\n\nGA4 key events and revenue reflect the property's configured definitions. Verify those definitions before making investment decisions.`;
}
