import { BetaAnalyticsDataClient, protos } from "@google-analytics/data";
import { comparisonDateWindow, type ComparisonMode } from "./dates.js";
import { withRetry } from "./resilience.js";
import type { Ga4EvidenceRow, Ga4Report } from "./types.js";
type RunReport=()=>Promise<protos.google.analytics.data.v1beta.IRunReportResponse>;
export interface Ga4ReportInput {days?:number;rowLimit?:number;startDate?:string;endDate?:string;comparison?:ComparisonMode;country?:string;device?:string;landingPageFilter?:string;campaignFilter?:string;channelGroup?:string}

export async function buildGa4Report(input:Ga4ReportInput,runReport:RunReport):Promise<Ga4Report>{
 const propertyId=process.env.GA4_PROPERTY_ID??"unconfigured",days=Math.min(365,Math.max(1,input.days??28)),dates=comparisonDateWindow(input.startDate,input.endDate,days,input.comparison),response=await runReport();
 const rows:Ga4EvidenceRow[]=(response.rows??[]).map(row=>{const dimensions=row.dimensionValues??[],metrics=row.metricValues??[],sessions=Number(metrics[0]?.value??0),keyEvents=Number(metrics[2]?.value??0);return {sourceMedium:dimensions[0]?.value??"",channelGroup:dimensions[1]?.value??"",campaign:dimensions[2]?.value??"",landingPage:dimensions[3]?.value??"",country:dimensions[4]?.value??"",device:dimensions[5]?.value??"",sessions,users:Number(metrics[1]?.value??0),keyEvents,revenue:Number(metrics[3]?.value??0),keyEventsPerSession:sessions?keyEvents/sessions:0}});
 const sampled=Boolean(response.metadata?.samplingMetadatas?.length),warnings=["GA4 key events and revenue reflect the property's configured definitions; verify them before investment decisions.",...(sampled?["GA4 reports this response as sampled."]:[])];
 const markdown=`# GA4 Acquisition & Landing Page Report\n\n**Property:** ${propertyId}  \n**Period:** ${dates.startDate} → ${dates.endDate}  \n**Rows:** ${rows.length}  \n**Sampled:** ${sampled?"Yes":"No"}\n\n| Source / medium | Campaign | Landing page | Sessions | Users | Key events | Key events / session | Revenue |\n|---|---|---|---:|---:|---:|---:|---:|\n${rows.map(row=>`| ${row.sourceMedium.replaceAll("|","\\|")} | ${row.campaign.replaceAll("|","\\|")} | ${row.landingPage.replaceAll("|","\\|")} | ${row.sessions} | ${row.users} | ${row.keyEvents} | ${row.keyEventsPerSession.toFixed(2)} | ${row.revenue.toFixed(2)} |`).join("\n")}\n\n${warnings.join(" ")}`;
 return {meta:{source:"ga4",property:propertyId,startDate:dates.startDate,endDate:dates.endDate,retrievedAt:new Date().toISOString(),rowCount:rows.length,partial:sampled,sampled,quota:response.propertyQuota as Record<string,unknown>|undefined,warnings},rows,markdown};
}

export async function ga4AcquisitionReport(input:Ga4ReportInput):Promise<Ga4Report>{
 const propertyId=process.env.GA4_PROPERTY_ID;if(!propertyId)throw new Error("GA4_PROPERTY_ID is not configured");if(!process.env.GOOGLE_APPLICATION_CREDENTIALS)throw new Error("GOOGLE_APPLICATION_CREDENTIALS is not configured");
 const days=Math.min(365,Math.max(1,input.days??28)),rowLimit=Math.min(10000,Math.max(1,input.rowLimit??50)),dates=comparisonDateWindow(input.startDate,input.endDate,days,input.comparison),client=new BetaAnalyticsDataClient(),expressions=[input.country?{filter:{fieldName:"country",stringFilter:{value:input.country,matchType:"EXACT"}}}:undefined,input.device?{filter:{fieldName:"deviceCategory",stringFilter:{value:input.device,matchType:"EXACT"}}}:undefined,input.landingPageFilter?{filter:{fieldName:"landingPagePlusQueryString",stringFilter:{value:input.landingPageFilter,matchType:"CONTAINS",caseSensitive:false}}}:undefined,input.campaignFilter?{filter:{fieldName:"sessionCampaignName",stringFilter:{value:input.campaignFilter,matchType:"CONTAINS",caseSensitive:false}}}:undefined,input.channelGroup?{filter:{fieldName:"sessionDefaultChannelGroup",stringFilter:{value:input.channelGroup,matchType:"EXACT"}}}:undefined].filter(Boolean) as protos.google.analytics.data.v1beta.IFilterExpression[];
 const call=async(startDate:string,endDate:string)=>{const [response]=await withRetry(()=>client.runReport({property:`properties/${propertyId}`,dateRanges:[{startDate,endDate}],dimensions:[{name:"sessionSourceMedium"},{name:"sessionDefaultChannelGroup"},{name:"sessionCampaignName"},{name:"landingPagePlusQueryString"},{name:"country"},{name:"deviceCategory"}],dimensionFilter:expressions.length?{andGroup:{expressions}}:undefined,metrics:[{name:"sessions"},{name:"totalUsers"},{name:"keyEvents"},{name:"totalRevenue"}],orderBys:[{metric:{metricName:"sessions"},desc:true}],limit:rowLimit,returnPropertyQuota:true},{timeout:15000}));return response},current=await call(dates.startDate,dates.endDate),report=await buildGa4Report(input,async()=>current),previous=await call(dates.previousStartDate,dates.previousEndDate),metricTotal=(response:protos.google.analytics.data.v1beta.IRunReportResponse,index:number)=>(response.rows??[]).reduce((sum,row)=>sum+Number(row.metricValues?.[index]?.value??0),0),currentSessions=metricTotal(current,0),previousSessions=metricTotal(previous,0),currentKeyEvents=metricTotal(current,2),previousKeyEvents=metricTotal(previous,2);
 report.meta.comparison={mode:input.comparison??"previous_period",startDate:dates.previousStartDate,endDate:dates.previousEndDate,currentSessions,previousSessions,sessionChange:previousSessions?(currentSessions-previousSessions)/previousSessions:null,currentKeyEvents,previousKeyEvents,keyEventChange:previousKeyEvents?(currentKeyEvents-previousKeyEvents)/previousKeyEvents:null};report.markdown+=`\n\n## Comparison\n\n| Metric | Current | Comparison | Change |\n|---|---:|---:|---:|\n| Sessions | ${currentSessions} | ${previousSessions} | ${report.meta.comparison.sessionChange===null?"N/A":(report.meta.comparison.sessionChange*100).toFixed(1)+"%"} |\n| Key events | ${currentKeyEvents} | ${previousKeyEvents} | ${report.meta.comparison.keyEventChange===null?"N/A":(report.meta.comparison.keyEventChange*100).toFixed(1)+"%"} |`;return report;
}
