import { google } from "googleapis";
import { createHash } from "node:crypto";
import { completedDateWindow } from "./dates.js";
import { classifyGoogleError, withRetry } from "./resilience.js";
export type GoogleAdsView="campaign"|"ad_group"|"search_term"|"landing_page"|"geography";
export interface GoogleAdsRow {view:GoogleAdsView;campaign:string;adGroup:string;dimension:string;device:string;geography:string;landingPage:string;impressions:number;clicks:number;spend:number;conversions:number;conversionValue:number;impressionShare:number|null;lostImpressionShare:number|null}
export interface GoogleAdsReport {meta:{source:"google_ads";customerId:string;startDate:string;endDate:string;retrievedAt:string;rowCount:number;view:GoogleAdsView;readOnly:true;warnings:string[]};rows:GoogleAdsRow[];markdown:string}
const cleanId=(value:string)=>value.replaceAll("-","");
const queryFor=(view:GoogleAdsView,startDate:string,endDate:string,filter:string|undefined,rowLimit:number)=>{
 const where=[`segments.date BETWEEN '${startDate}' AND '${endDate}'`,filter?`campaign.name LIKE '%${filter.replaceAll("'","\\'")}%'`:undefined].filter(Boolean).join(" AND "),limit=`LIMIT ${rowLimit}`;
 const baseMetrics="metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.conversions_value",metrics=view==="campaign"?`${baseMetrics}, metrics.search_impression_share, metrics.search_budget_lost_impression_share`:baseMetrics;
 if(view==="campaign")return `SELECT campaign.id, campaign.name, segments.device, ${metrics} FROM campaign WHERE ${where} ${limit}`;
 if(view==="ad_group")return `SELECT campaign.name, ad_group.id, ad_group.name, segments.device, ${metrics} FROM ad_group WHERE ${where} ${limit}`;
 if(view==="search_term")return `SELECT campaign.name, ad_group.name, search_term_view.search_term, segments.device, ${metrics} FROM search_term_view WHERE ${where} ${limit}`;
 if(view==="landing_page")return `SELECT campaign.name, landing_page_view.unexpanded_final_url, segments.device, ${metrics} FROM landing_page_view WHERE ${where} ${limit}`;
 return `SELECT campaign.name, geographic_view.country_criterion_id, segments.device, ${metrics} FROM geographic_view WHERE ${where} ${limit}`;
};
const num=(value:unknown)=>Number(value??0),share=(value:unknown)=>value===undefined||value===null?null:Number(value);
export function parseGoogleAdsRows(view:GoogleAdsView,payload:unknown):GoogleAdsRow[]{const batches=Array.isArray(payload)?payload:[payload],results=batches.flatMap(batch=>((batch as {results?:unknown[]})?.results??[]));return results.map(item=>{const row=item as Record<string,any>,metrics=row.metrics??{};return {view,campaign:row.campaign?.name??"",adGroup:row.adGroup?.name??"",dimension:view==="search_term"?row.searchTermView?.searchTerm??"":view==="landing_page"?row.landingPageView?.unexpandedFinalUrl??"":view==="geography"?String(row.geographicView?.countryCriterionId??""):row.adGroup?.name??row.campaign?.name??"",device:row.segments?.device??"",geography:view==="geography"?String(row.geographicView?.countryCriterionId??""):"",landingPage:view==="landing_page"?row.landingPageView?.unexpandedFinalUrl??"":"",impressions:num(metrics.impressions),clicks:num(metrics.clicks),spend:num(metrics.costMicros)/1_000_000,conversions:num(metrics.conversions),conversionValue:num(metrics.conversionsValue),impressionShare:share(metrics.searchImpressionShare),lostImpressionShare:share(metrics.searchBudgetLostImpressionShare)}})}
export async function googleAdsReport(input:{view?:GoogleAdsView;startDate?:string;endDate?:string;campaignFilter?:string;rowLimit?:number}):Promise<GoogleAdsReport>{
 const required=["GOOGLE_ADS_CUSTOMER_ID","GOOGLE_ADS_DEVELOPER_TOKEN","GOOGLE_ADS_CLIENT_ID","GOOGLE_ADS_CLIENT_SECRET","GOOGLE_ADS_REFRESH_TOKEN"] as const,missing=required.filter(key=>!process.env[key]);if(missing.length)throw new Error(`Google Ads is not configured; missing ${missing.join(", ")}`);
 const customerId=cleanId(process.env.GOOGLE_ADS_CUSTOMER_ID!),view=input.view??"campaign",dates=completedDateWindow(input.startDate,input.endDate),rowLimit=Math.min(10000,Math.max(1,input.rowLimit??100)),oauth=new google.auth.OAuth2(process.env.GOOGLE_ADS_CLIENT_ID,process.env.GOOGLE_ADS_CLIENT_SECRET);oauth.setCredentials({refresh_token:process.env.GOOGLE_ADS_REFRESH_TOKEN});
 const access=await withRetry(()=>oauth.getAccessToken()),token=typeof access==="string"?access:access.token;if(!token)throw new Error("Google Ads OAuth did not return an access token");
 const headers:Record<string,string>={authorization:`Bearer ${token}`,"developer-token":process.env.GOOGLE_ADS_DEVELOPER_TOKEN!,"content-type":"application/json"};if(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID)headers["login-customer-id"]=cleanId(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID);const response=await withRetry(async()=>{const res=await fetch(`https://googleads.googleapis.com/v24/customers/${customerId}/googleAds:searchStream`,{method:"POST",headers,body:JSON.stringify({query:queryFor(view,dates.startDate,dates.endDate,input.campaignFilter,rowLimit)}),signal:AbortSignal.timeout(20000)});if(!res.ok){const error=new Error(`Google Ads API returned ${res.status}: ${(await res.text()).slice(0,300)}`) as Error&{status:number};error.status=res.status;throw error}return res.json()}).catch(error=>{throw classifyGoogleError(error)}),rows=parseGoogleAdsRows(view,response),warnings=["Google Ads conversion metrics depend on the account's configured conversion actions and attribution settings.","Impression-share metrics are requested only for the campaign view because field compatibility differs by GAQL resource.","This connector is read-only and contains no mutation operations."];
 const markdown=`# Google Ads — ${view.replaceAll("_"," ")} report\n\n**Customer:** ${customerId}  \n**Period:** ${dates.startDate} → ${dates.endDate}  \n**Rows:** ${rows.length}\n\n| Campaign | Ad group / dimension | Device | Impressions | Clicks | Spend | Conversions | Conversion value | Impression share | Lost IS |\n|---|---|---|---:|---:|---:|---:|---:|---:|---:|\n${rows.map(row=>`| ${row.campaign} | ${row.dimension} | ${row.device} | ${row.impressions} | ${row.clicks} | ${row.spend.toFixed(2)} | ${row.conversions.toFixed(2)} | ${row.conversionValue.toFixed(2)} | ${row.impressionShare===null?"N/A":(row.impressionShare*100).toFixed(1)+"%"} | ${row.lostImpressionShare===null?"N/A":(row.lostImpressionShare*100).toFixed(1)+"%"} |`).join("\n")}\n\n${warnings.join(" ")}`;
 return {meta:{source:"google_ads",customerId,startDate:dates.startDate,endDate:dates.endDate,retrievedAt:new Date().toISOString(),rowCount:rows.length,view,readOnly:true,warnings},rows,markdown};
}
export const googleAdsEvidenceId=(parts:unknown[])=>createHash("sha256").update(JSON.stringify(parts)).digest("hex").slice(0,16);
