import { google } from "googleapis";
import { completedDateWindow } from "./dates.js";
const moneyless=(value:number)=>Number.isFinite(value)?value:0;
export async function searchConsoleReport(input:{startDate?:string;endDate?:string;rowLimit?:number}):Promise<string>{
 const siteUrl=process.env.GSC_SITE_URL;if(!siteUrl)throw new Error("GSC_SITE_URL is not configured");if(!process.env.GOOGLE_APPLICATION_CREDENTIALS)throw new Error("GOOGLE_APPLICATION_CREDENTIALS is not configured");
 const dates=completedDateWindow(input.startDate,input.endDate),rowLimit=Math.min(25000,Math.max(1,input.rowLimit??50)),auth=new google.auth.GoogleAuth({scopes:["https://www.googleapis.com/auth/webmasters.readonly"]}),client=google.searchconsole({version:"v1",auth});
 const query=async(startDate:string,endDate:string)=>{const response=await client.searchanalytics.query({siteUrl,requestBody:{startDate,endDate,dimensions:["query","page"],rowLimit,dataState:"final"}});return response.data.rows??[]};
 const [current,previous]=await Promise.all([query(dates.startDate,dates.endDate),query(dates.previousStartDate,dates.previousEndDate)]),prior=new Map(previous.map(row=>[(row.keys??[]).join("\u0000"),moneyless(row.impressions??0)]));
 const rows=current.map(row=>{const [searchQuery="",page=""]=row.keys??[],impressions=moneyless(row.impressions??0),previousImpressions=prior.get((row.keys??[]).join("\u0000"))??0,growth=previousImpressions?(impressions-previousImpressions)/previousImpressions:null;return {searchQuery,page,clicks:moneyless(row.clicks??0),impressions,ctr:moneyless(row.ctr??0),position:moneyless(row.position??0),previousImpressions,growth}}).sort((a,b)=>b.impressions-a.impressions).slice(0,rowLimit);
 return `# Google Search Console Report\n\n**Site:** ${siteUrl}  \n**Current:** ${dates.startDate} → ${dates.endDate}  \n**Comparison:** ${dates.previousStartDate} → ${dates.previousEndDate}  \n**Rows:** ${rows.length}\n\n| Query | Page | Clicks | Impressions | CTR | Position | Prior impressions | Growth |\n|---|---|---:|---:|---:|---:|---:|---:|\n${rows.map(row=>`| ${row.searchQuery.replaceAll("|","\\|")} | ${row.page.replaceAll("|","\\|")} | ${row.clicks} | ${row.impressions} | ${(row.ctr*100).toFixed(1)}% | ${row.position.toFixed(1)} | ${row.previousImpressions} | ${row.growth===null?"New / unavailable":`${(row.growth*100).toFixed(1)}%`} |`).join("\n")}\n\nSearch Console may return top rows rather than every row. Treat this as demand evidence, not revenue attribution.`;
}
