import {readFileSync} from "node:fs";
import {z} from "zod";
import type {EvidenceSource} from "../evidence/schema.js";
import {METRIC_DEFINITIONS_VERSION} from "./types.js";

const sourceValue=z.object({source:z.string().min(1),value:z.string().min(1)}).strict();
const identity=z.object({canonical_key:z.string().regex(/^[a-z0-9][a-z0-9._:-]*$/),label:z.string().min(1),source_values:z.array(sourceValue).min(1)}).strict();
const stage=z.object({canonical_stage:z.enum(["lead","mql","sql","opportunity","closed_won","closed_lost"]),source_values:z.array(sourceValue).min(1)}).strict();
export const semanticConfigSchema=z.object({version:z.literal(1),definitions_version:z.literal(METRIC_DEFINITIONS_VERSION),currency:z.string().regex(/^[A-Z]{3}$/),timezone:z.string().min(1),governance:z.object({owner:z.string().min(1),approved_at:z.string().datetime()}).strict(),lifecycle:z.object({stages:z.array(stage).default([])}).strict(),identities:z.object({campaigns:z.array(identity).default([]),landing_pages:z.array(identity).default([])}).strict(),channel_groups:z.array(z.object({canonical_key:z.string().min(1),label:z.string().min(1),source_values:z.array(sourceValue).min(1)}).strict()).default([])}).strict();
export type SemanticConfig=z.infer<typeof semanticConfigSchema>;
export const defaultSemanticConfig=():SemanticConfig=>({version:1,definitions_version:METRIC_DEFINITIONS_VERSION,currency:process.env.CURRENCY_CODE??"USD",timezone:process.env.MARKETING_TIMEZONE??"UTC",governance:{owner:"unconfigured",approved_at:"1970-01-01T00:00:00.000Z"},lifecycle:{stages:[]},identities:{campaigns:[],landing_pages:[]},channel_groups:[]});
export const parseSemanticConfig=(value:unknown):SemanticConfig=>semanticConfigSchema.parse(value);
export function loadSemanticConfig(path=process.env.MARKETING_SEMANTIC_FILE):SemanticConfig{if(!path)return defaultSemanticConfig();try{return parseSemanticConfig(JSON.parse(readFileSync(path,"utf8")))}catch(error){throw new Error(`MARKETING_SEMANTIC_FILE is invalid: ${error instanceof Error?error.message:"Unknown error"}`)}}
const safeKey=(value:string)=>value.trim().toLowerCase().normalize("NFKD").replace(/[^a-z0-9._:-]+/g,"-").replace(/^-+|-+$/g,"")||"unknown";
export function resolveCanonicalIdentity(kind:"campaigns"|"landing_pages",source:EvidenceSource,value:string|undefined,config:SemanticConfig){if(!value)return undefined;const normalized=value.trim().toLowerCase(),match=config.identities[kind].find(item=>item.source_values.some(candidate=>candidate.source===source&&candidate.value.trim().toLowerCase()===normalized));return match?{canonicalKey:match.canonical_key,label:match.label,mapping:"configured" as const,confidence:1,source,value}:{canonicalKey:`source:${source}:${kind}:${safeKey(value)}`,label:value,mapping:"unmapped" as const,confidence:.25,source,value}}
export function resolveLifecycleStage(source:EvidenceSource,value:string|undefined,config:SemanticConfig){if(!value)return undefined;const normalized=value.trim().toLowerCase(),match=config.lifecycle.stages.find(item=>item.source_values.some(candidate=>candidate.source===source&&candidate.value.trim().toLowerCase()===normalized));return match?{canonicalStage:match.canonical_stage,mapping:"configured" as const,confidence:1,source,value}:{canonicalStage:undefined,mapping:"unmapped" as const,confidence:0,source,value}}
export function resolveChannelGroup(source:EvidenceSource,value:string|undefined,config:SemanticConfig){if(!value)return undefined;const normalized=value.trim().toLowerCase(),match=config.channel_groups.find(item=>item.source_values.some(candidate=>candidate.source===source&&candidate.value.trim().toLowerCase()===normalized));return match?{canonicalKey:match.canonical_key,label:match.label,mapping:"configured" as const,confidence:1,source,value}:{canonicalKey:`source:${source}:channel:${safeKey(value)}`,label:value,mapping:"unmapped" as const,confidence:.25,source,value}}
