import { accessSync, constants, cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { createInterface } from "node:readline/promises";
import process from "node:process";
const root=resolve(dirname(fileURLToPath(import.meta.url)),".."),args=new Set(process.argv.slice(2)),rl=createInterface({input:process.stdin,output:process.stdout});
const ask=async(label,fallback="")=>(await rl.question(`${label}${fallback?` [${fallback}]`:""}: `)).trim()||fallback;
const credential=await ask("Absolute path to Google service-account JSON");if(!credential.startsWith("/"))throw new Error("Credential path must be absolute");accessSync(credential,constants.R_OK);const parsed=JSON.parse(readFileSync(credential,"utf8"));if(parsed.type!=="service_account"||!parsed.client_email||!parsed.private_key)throw new Error("Credential file is not a complete Google service-account JSON");
const gsc=await ask("Search Console property","sc-domain:example.com"),ga4=await ask("Numeric GA4 Property ID");if(!/^\d+$/.test(ga4))throw new Error("GA4 Property ID must be numeric, not a G- measurement ID");const mapping=await ask("Optional absolute marketing mapping JSON path","");if(mapping&&!existsSync(mapping))throw new Error("Mapping file does not exist");
const env={DATA_MODE:"demo",AI_PROVIDER:"none",CURRENCY_CODE:"USD",NUMBER_LOCALE:"en-US",GOOGLE_APPLICATION_CREDENTIALS:credential,GSC_SITE_URL:gsc,GA4_PROPERTY_ID:ga4,...(mapping?{MARKETING_MAPPING_FILE:mapping}:{})};
if(!args.has("--google-only")&&(await ask("Configure Google Ads read-only reporting? (y/N)","N")).toLowerCase()==="y"){env.GOOGLE_ADS_CUSTOMER_ID=await ask("Google Ads customer ID");env.GOOGLE_ADS_DEVELOPER_TOKEN=await ask("Google Ads developer token");env.GOOGLE_ADS_CLIENT_ID=await ask("Google Ads OAuth client ID");env.GOOGLE_ADS_CLIENT_SECRET=await ask("Google Ads OAuth client secret");env.GOOGLE_ADS_REFRESH_TOKEN=await ask("Google Ads OAuth refresh token");const login=await ask("Optional manager login customer ID","");if(login)env.GOOGLE_ADS_LOGIN_CUSTOMER_ID=login}
if(!args.has("--google-only")){const crm=(await ask("CRM provider: none, hubspot, salesforce, or csv","none")).toLowerCase();if(crm==="hubspot"){env.CRM_PROVIDER="hubspot";env.HUBSPOT_ACCESS_TOKEN=await ask("HubSpot private-app access token")}else if(crm==="salesforce"){env.CRM_PROVIDER="salesforce";env.SALESFORCE_INSTANCE_URL=await ask("Salesforce HTTPS instance URL");env.SALESFORCE_ACCESS_TOKEN=await ask("Salesforce OAuth access token")}else if(crm==="csv"){env.CRM_PROVIDER="csv";env.GENERIC_CRM_CSV=await ask("Absolute generic CRM CSV path");if(!env.GENERIC_CRM_CSV.startsWith("/")||!existsSync(env.GENERIC_CRM_CSV))throw new Error("Generic CRM CSV path must be absolute and readable")}}
const server={command:process.execPath,args:[join(root,"dist/index.js")],env},output=join(root,"setup-output");mkdirSync(output,{recursive:true,mode:0o700});
writeFileSync(join(output,"claude-desktop-snippet.json"),`${JSON.stringify({mcpServers:{"general-marketing-intelligence":server}},null,2)}\n`,{mode:0o600});writeFileSync(join(output,"codex-command.txt"),`codex mcp add general-marketing-intelligence ${Object.entries(env).map(([key,value])=>`--env ${key}=${JSON.stringify(value)}`).join(" ")} -- ${JSON.stringify(process.execPath)} ${JSON.stringify(join(root,"dist/index.js"))}\n`,{mode:0o600});
if(args.has("--apply-claude")){const configPath=join(homedir(),"Library/Application Support/Claude/claude_desktop_config.json"),config=existsSync(configPath)?JSON.parse(readFileSync(configPath,"utf8")):{};if(existsSync(configPath))cpSync(configPath,`${configPath}.backup-${new Date().toISOString().replace(/[:.]/g,"-")}`);config.mcpServers={...(config.mcpServers??{}),"general-marketing-intelligence":server};mkdirSync(dirname(configPath),{recursive:true});writeFileSync(configPath,`${JSON.stringify(config,null,2)}\n`,{mode:0o600});console.log("Claude Desktop configuration updated with a timestamped backup.")}
console.log(`Setup files written privately to ${output}`);console.log(`Service account validated for ${parsed.client_email}. Credential contents were not printed.`);console.log("Run npm run doctor, then fully restart Claude or Codex.");rl.close();
