export const adPlatforms=["google_ads","meta_ads","linkedin_ads","microsoft_ads","youtube_ads","programmatic"] as const;
export const adCampaignTypes=["search","shopping","performance_max","display","video","demand_gen","social_prospecting","social_retargeting","lead_generation","abm","programmatic_display"] as const;
export const adObjectives=["awareness","traffic","leads","pipeline","revenue"] as const;
export type AdPlatform=typeof adPlatforms[number];
export type AdCampaignType=typeof adCampaignTypes[number];
export type AdObjective=typeof adObjectives[number];
export interface AdCampaignInput {name:string;platform:AdPlatform;campaignType:AdCampaignType;objective:AdObjective;dailyBudget?:number;spend:number;impressions:number;clicks:number;conversions:number;conversionValue?:number;qualifiedLeads?:number;pipelineValue?:number;revenue?:number;frequency?:number;daysObserved:number;daysSinceLastChange?:number;conversionLagDays?:number;targetCpa?:number;targetRoas?:number}
export interface AdStrategyResult {name:string;decision:"INCREASE_TEST"|"DECREASE_TEST"|"HOLD"|"FIX_BEFORE_SPEND";suggestedChangePct:number;confidence:"LOW"|"MEDIUM"|"HIGH";baselineConversionRate:number;baselineStrength:number;posteriorConversionRate:number;posteriorStandardError:number;observedCpa:number|null;observedRoas:number|null;modeledCpa:number|null;modeledRoas:number|null;commercialRoas:number|null;evidence:string[];strategy:string[];guardrails:string[];humanDecisionRequired:true;calculation:"bayesian_shrinkage_and_bounded_rules"}

const strategies:Record<AdCampaignType,string[]>={
 search:["Review search terms and negatives before expanding match types.","Protect brand/non-brand separation and query-to-landing-page message match."],
 shopping:["Review feed coverage, product economics and out-of-stock waste.","Segment products by margin and commercial priority before increasing spend."],
 performance_max:["Inspect channel, asset-group, search-category and product evidence before treating blended ROAS as causal.","Protect brand controls and compare incremental value against standard campaign coverage."],
 display:["Review placements, viewability, frequency and post-view attribution before scaling.","Use exclusions and incrementality evidence to control low-quality reach."],
 video:["Evaluate reach, completed views, attention and downstream lift by creative cohort.","Separate prospecting from remarketing and rotate fatigued creative."],
 demand_gen:["Evaluate creative, audience and landing-page combinations separately.","Judge assisted outcomes cautiously and preserve a holdout where practical."],
 social_prospecting:["Test one audience, offer and creative hypothesis at a time.","Watch frequency, creative fatigue and qualified downstream conversion."],
 social_retargeting:["Cap frequency and exclude converted or recently contacted users.","Measure incremental recovery rather than claiming all view-through outcomes."],
 lead_generation:["Prioritize qualified-lead and pipeline rates over platform CPL.","Audit form friction, spam, enrichment and sales follow-up latency."],
 abm:["Judge account reach, engaged buying groups and opportunity progression.","Avoid optimizing a low-volume ABM campaign solely on form conversions."],
 programmatic_display:["Audit supply paths, placements, fraud controls and viewability.","Require incrementality evidence before increasing broad reach."]
};
const finite=(value:number|undefined)=>Number.isFinite(value)?Number(value):0;
const ratio=(a:number,b:number)=>b>0?a/b:null;
export function analyzeAdCampaign(input:AdCampaignInput,maxDailyChangePct=10,prior={alpha:1,beta:19}):AdStrategyResult{
 const clicks=Math.max(0,finite(input.clicks)),conversions=Math.max(0,finite(input.conversions)),spend=Math.max(0,finite(input.spend)),conversionValue=Math.max(0,finite(input.conversionValue)),pipeline=Math.max(0,finite(input.pipelineValue)),revenue=Math.max(0,finite(input.revenue));
 // Weakly informative Beta(1,19) prior represents a 5% baseline and prevents tiny samples from appearing certain.
 const binomialConversions=Math.min(clicks,conversions),alpha=prior.alpha+binomialConversions,beta=prior.beta+Math.max(0,clicks-binomialConversions),posteriorConversionRate=alpha/(alpha+beta),posteriorStandardError=Math.sqrt(alpha*beta/((alpha+beta)**2*(alpha+beta+1))),baselineConversionRate=prior.alpha/(prior.alpha+prior.beta),baselineStrength=prior.alpha+prior.beta;
 const observedCpa=ratio(spend,conversions),observedRoas=input.conversionValue===undefined?null:ratio(conversionValue,spend),expectedConversions=posteriorConversionRate*clicks,modeledCpa=ratio(spend,expectedConversions),valuePerConversion=ratio(conversionValue,conversions),modeledRoas=valuePerConversion===null?null:ratio(valuePerConversion*expectedConversions,spend),commercialSupplied=input.revenue!==undefined||input.pipelineValue!==undefined,commercialRoas=commercialSupplied?ratio(revenue||pipeline,spend):null,lag=Math.max(0,finite(input.conversionLagDays)),since=Math.max(0,finite(input.daysSinceLastChange)),mature=input.daysObserved>=Math.max(7,lag*2)&&since>=lag,qualified=finite(input.qualifiedLeads);
 const enough=clicks>=100&&conversions>=5&&mature,high=clicks>=500&&conversions>=20&&mature,confidence=high?"HIGH":enough?"MEDIUM":"LOW";
 let score=0;if(input.targetCpa&&modeledCpa!==null)score+=(input.targetCpa-modeledCpa)/input.targetCpa;if(input.targetRoas&&modeledRoas!==null)score+=(modeledRoas-input.targetRoas)/input.targetRoas;if(commercialRoas!==null)score+=commercialRoas>=1?.5:-.5;if(qualified>0)score+=.25;
 let decision:AdStrategyResult["decision"]="HOLD",suggestedChangePct=0;
 if(!mature||confidence==="LOW"){decision=spend>0&&clicks>=150&&conversions===0?"FIX_BEFORE_SPEND":"HOLD";suggestedChangePct=decision==="FIX_BEFORE_SPEND"?-Math.min(maxDailyChangePct,10):0}
 else if(score>=.35){decision="INCREASE_TEST";suggestedChangePct=Math.min(maxDailyChangePct,Math.max(3,Math.round(score*10)))}
 else if(score<=-.35){decision="DECREASE_TEST";suggestedChangePct=-Math.min(maxDailyChangePct,Math.max(3,Math.round(Math.abs(score)*10)))}
 const evidence=[`${input.daysObserved} observed days, ${clicks} clicks, ${conversions} platform conversions and ${spend.toFixed(2)} spend.`,...(conversions>clicks?["Conversions exceed clicks, so the Bayesian rate uses clicks as its success ceiling; CPA and ROAS retain reported conversions."]:[]),commercialRoas===null?"No CRM pipeline or revenue efficiency was supplied.":`Commercial value/spend is ${commercialRoas.toFixed(2)}x.`,mature?"The observation window clears the supplied conversion-lag guardrail.":"Recent data may be immature relative to conversion lag or the last material change."];
 const guardrails=[`Suggested change is capped at ±${maxDailyChangePct}% and is a recommendation only.`,"Do not make another budget decision until the conversion-lag window has elapsed.","Prefer qualified pipeline or revenue over platform conversions when available.","Require a human to review attribution, tracking and campaign context before acting."];
 return {name:input.name,decision,suggestedChangePct,confidence,baselineConversionRate,baselineStrength,posteriorConversionRate,posteriorStandardError,observedCpa,observedRoas,modeledCpa,modeledRoas,commercialRoas,evidence,strategy:strategies[input.campaignType],guardrails,humanDecisionRequired:true,calculation:"bayesian_shrinkage_and_bounded_rules"};
}
export function analyzeAdPortfolio(campaigns:AdCampaignInput[],maxDailyChangePct=10){const groups=new Map<string,AdCampaignInput[]>();for(const campaign of campaigns){const key=`${campaign.platform}|${campaign.campaignType}|${campaign.objective}`;groups.set(key,[...(groups.get(key)??[]),campaign])}return campaigns.map(campaign=>{const peers=groups.get(`${campaign.platform}|${campaign.campaignType}|${campaign.objective}`)??[],clicks=peers.reduce((sum,row)=>sum+row.clicks,0),successes=peers.reduce((sum,row)=>sum+Math.min(row.clicks,row.conversions),0),useAccount=peers.length>=2&&clicks>=100,rate=useAccount?successes/clicks:.05,strength=useAccount?Math.min(100,Math.max(20,clicks*.1)):20;return analyzeAdCampaign(campaign,maxDailyChangePct,{alpha:Math.max(.01,rate*strength),beta:Math.max(.01,(1-rate)*strength)})}).sort((a,b)=>b.suggestedChangePct-a.suggestedChangePct)}
const pct=(value:number)=>`${(value*100).toFixed(2)}%`,number=(value:number|null)=>value===null?"Unavailable":value.toFixed(2);
export function renderAdStrategy(results:AdStrategyResult[]){return `# Advertising Strategy Review\n\n> Recommendation only. No campaign, bid or budget mutation is implemented.\n\n${results.map(result=>`## ${result.name}\n\n**Decision:** ${result.decision}  \n**Suggested daily budget test:** ${result.suggestedChangePct>0?"+":""}${result.suggestedChangePct}%  \n**Confidence:** ${result.confidence}  \n**Account/type baseline:** ${pct(result.baselineConversionRate)} from ${result.baselineStrength.toFixed(0)} equivalent observations  \n**Posterior conversion rate:** ${pct(result.posteriorConversionRate)} ± ${pct(result.posteriorStandardError)} standard error  \n**Observed / model-adjusted CPA:** ${number(result.observedCpa)} / ${number(result.modeledCpa)}  \n**Observed / model-adjusted platform ROAS:** ${number(result.observedRoas)} / ${number(result.modeledRoas)}  \n**Commercial value/spend:** ${number(result.commercialRoas)}\n\n### Observed evidence\n${result.evidence.map(value=>`- ${value}`).join("\n")}\n\n### Strategy\n${result.strategy.map(value=>`- ${value}`).join("\n")}\n\n### Guardrails\n${result.guardrails.map(value=>`- ${value}`).join("\n")}\n\n**Human decision required:** YES`).join("\n\n")}\n\n## Statistical boundary\n\nThe account/type empirical baseline is estimated only when at least two comparable campaigns and 100 clicks exist; otherwise a weak 5% baseline is used. The posterior feeds target CPA/ROAS comparison but does not prove incrementality or causal lift.`}
