#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { growthSnapshot } from "./tools/growthSnapshot.js";
import { findSeoOpportunities } from "./tools/seoOpportunities.js";
import { auditPaidSearch } from "./tools/paidSearchAudit.js";
import { opportunityRadar } from "./tools/opportunityRadar.js";
import { weeklyGrowthBrief } from "./tools/weeklyGrowthBrief.js";
import { paidPerformanceReview, budgetAllocator, designPaidExperiment } from "./tools/performanceAgent.js";
import { assetTypes, contentStrategy, createCampaignAsset } from "./tools/contentAgent.js";
import { buildGrowthBet } from "./tools/growthBet.js";
import { connectionStatus } from "./tools/connectionStatus.js";
import { enhanceMarketingOutput } from "./ai/enhance.js";
import { buildEvidencePacket } from "./ai/evidence.js";
import { searchConsoleReport } from "./connectors/google/searchConsole.js";
import { ga4AcquisitionReport } from "./connectors/google/ga4.js";

const server=new McpServer({name:"general-marketing-intelligence",version:"1.0.0"});
const segment=z.string().min(1).optional();
const text=(value:string)=>({content:[{type:"text" as const,text:value}]});

server.registerTool("growth_snapshot",{title:"Growth Snapshot",description:"What changed across acquisition, and what matters commercially? Uses configured CSV data.",inputSchema:{date_range:z.string().optional().describe("Optional label for the reporting period."),segment}},({segment})=>text(growthSnapshot(segment)));
server.registerTool("find_seo_opportunities",{title:"Find SEO Opportunities",description:"Which organic-search themes deserve a landing page, content asset or conversion improvement? Uses configured CSV data.",inputSchema:{segment,limit:z.number().int().min(1).max(10).default(5)}},({segment,limit})=>text(findSeoOpportunities(segment,limit)));
server.registerTool("audit_paid_search",{title:"Audit Paid Search",description:"Where should paid-search budget increase, decrease or pause based on SQL and pipeline quality? Uses configured CSV data.",inputSchema:{segment}},({segment})=>text(auditPaidSearch(segment)));
server.registerTool("opportunity_radar",{title:"Opportunity Radar",description:"What emerging demand should become a coordinated digital, content, field and sales motion? Uses configured CSV data.",inputSchema:{limit:z.number().int().min(1).max(5).default(3)}},async({limit})=>{const fallback=opportunityRadar(limit);return text(await enhanceMarketingOutput("Interpret why the deterministic opportunity ranking matters commercially. Preserve ranking; label any alternative interpretation.",fallback,buildEvidencePacket("opportunity_radar",{limit},fallback)))});
server.registerTool("weekly_growth_brief",{title:"Weekly Growth Brief",description:"What are the five highest-priority marketing actions for next week? Uses configured CSV data.",inputSchema:{}},async()=>{const fallback=weeklyGrowthBrief();return text(await enhanceMarketingOutput("Synthesize a direct Head-of-Marketing weekly brief. Prioritize action and pipeline; do not change the five deterministic actions.",fallback,buildEvidencePacket("weekly_growth_brief",{},fallback)))});
server.registerTool("paid_performance_review",{title:"Paid Performance Review",description:"What is happening across paid acquisition, and which signals matter commercially?",inputSchema:{}},async()=>{const fallback=paidPerformanceReview();return text(await enhanceMarketingOutput("Synthesize campaign economics into a Head-of-Marketing view. Identify misleading volume, risks and assumptions without changing calculated metrics.",fallback,buildEvidencePacket("paid_performance_review",{},fallback)))});
server.registerTool("budget_allocator",{title:"Budget Allocator",description:"Where should the next incremental marketing budget go, with reserves and guardrails?",inputSchema:{incremental_budget:z.number().positive()}},async({incremental_budget})=>{const fallback=budgetAllocator(incremental_budget);return text(await enhanceMarketingOutput("Explain the deterministic allocation, risks, assumptions, confidence and evidence that would change it. Never alter any allocation amount.",fallback,buildEvidencePacket("budget_allocator",{incremental_budget},fallback)))});
server.registerTool("design_paid_experiment",{title:"Design Paid Experiment",description:"Design a controlled paid-acquisition validation test for a segment opportunity.",inputSchema:{segment:z.string().min(1),opportunity:z.string().min(2),budget:z.number().positive().optional()}},async({segment,opportunity,budget})=>{const fallback=designPaidExperiment(segment,opportunity,budget);return text(await enhanceMarketingOutput("Improve the audience hypothesis, messaging, campaign framing and experiment design while preserving deterministic budget, thresholds and review window.",fallback,buildEvidencePacket("design_paid_experiment",{segment,opportunity,budget},fallback)))});
server.registerTool("content_strategy",{title:"Content & Category Strategy",description:"Decide what narrative and assets should support a commercial opportunity before writing them.",inputSchema:{opportunity:z.string().min(2),segment:z.string().min(2),persona:z.string().optional(),funnel_stage:z.string().optional()}},async({opportunity,segment,persona,funnel_stage})=>{const fallback=contentStrategy(opportunity,segment,persona,funnel_stage);return text(await enhanceMarketingOutput("Develop the buyer question, category narrative, content architecture, funnel role and justified field-marketing implications.",fallback,buildEvidencePacket("content_strategy",{opportunity,segment,persona,funnel_stage},fallback)))});
server.registerTool("create_campaign_asset",{title:"Create Campaign Asset Brief",description:"Create a structured, proof-safe brief for one supported commercial marketing asset.",inputSchema:{asset_type:z.enum(assetTypes),opportunity:z.string().min(2),segment:z.string().min(2),persona:z.string().optional()}},async({asset_type,opportunity,segment,persona})=>{const fallback=createCampaignAsset(asset_type,opportunity,segment,persona);return text(await enhanceMarketingOutput(`Produce a polished ${asset_type} output from the verified brief. Never invent proof; preserve placeholders.`,fallback,buildEvidencePacket("create_campaign_asset",{asset_type,opportunity,segment,persona},fallback)))});
server.registerTool("build_growth_bet",{title:"Build Growth Bet",description:"Turn the strongest opportunity or a selected segment into one coordinated, measurable marketing motion.",inputSchema:{opportunity:z.string().optional(),segment:z.string().optional(),budget:z.number().positive().optional()}},async({opportunity,segment,budget})=>{const fallback=buildGrowthBet(opportunity,segment,budget);return text(await enhanceMarketingOutput("Synthesize the strategic thesis, channel coordination, sequencing, narrative, risks and 30-day reasoning. Preserve deterministic ranking, allocation, state, confidence and metrics.",fallback,buildEvidencePacket("build_growth_bet",{opportunity,segment,budget},fallback)))});
server.registerTool("connection_status",{title:"Connection Status",description:"Truthfully report demo-mode sources and readiness of future read-only platform adapters.",inputSchema:{}},()=>text(connectionStatus()));
server.registerTool("google_search_console_report",{title:"Google Search Console Report",description:"Read current Search Console query/page performance and compare impressions with the preceding period. Requires local Google credentials.",inputSchema:{start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),row_limit:z.number().int().min(1).max(25000).default(50)}},async({start_date,end_date,row_limit})=>{try{return text(await searchConsoleReport({startDate:start_date,endDate:end_date,rowLimit:row_limit}))}catch(error){return {content:[{type:"text" as const,text:`Google Search Console request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("ga4_acquisition_report",{title:"GA4 Acquisition Report",description:"Read GA4 acquisition, landing-page, key-event and revenue metrics. Requires local Google credentials.",inputSchema:{days:z.number().int().min(1).max(365).default(28),row_limit:z.number().int().min(1).max(10000).default(50)}},async({days,row_limit})=>{try{return text(await ga4AcquisitionReport({days,rowLimit:row_limit}))}catch(error){return {content:[{type:"text" as const,text:`GA4 request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});

await server.connect(new StdioServerTransport());
