import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { growthSnapshot } from "./tools/growthSnapshot.js";
import { findSeoOpportunities } from "./tools/seoOpportunities.js";
import { auditPaidSearch } from "./tools/paidSearchAudit.js";
import { opportunityRadar } from "./tools/opportunityRadar.js";
import { weeklyGrowthBrief } from "./tools/weeklyGrowthBrief.js";
import { paidPerformanceReview, budgetAllocator, designPaidExperiment } from "./tools/performanceAgent.js";
import { assetTypes, contentStrategy, createCampaignAsset } from "./tools/contentAgent.js";
import { buildGrowthBet } from "./tools/growthBet.js";
import { connectionStatus } from "./tools/connectionStatus.js";
import { enhanceMarketingOutput } from "./ai/enhance.js";
import { buildEvidencePacket } from "./ai/evidence.js";
import { searchConsoleReport } from "./connectors/google/searchConsole.js";
import { ga4AcquisitionReport } from "./connectors/google/ga4.js";
import { diagnoseSetup } from "./tools/diagnostics.js";
import { getLiveEvidence } from "./evidence/live.js";
import { renderLiveOpportunities } from "./evidence/normalize.js";
import { listSnapshots, saveSnapshot } from "./evidence/snapshots.js";
import { googleAdsReport } from "./connectors/google/googleAds.js";
import { hubspotFunnelReport } from "./connectors/crm/hubspot.js";
import { salesforceFunnelReport } from "./connectors/crm/salesforce.js";
import { genericCrmCsvReport } from "./connectors/crm/csv.js";
import { connectorCatalog } from "./connectors/catalog.js";
import { getCommercialBundle, renderCommercialSignals } from "./evidence/commercial.js";
import { brandVsNonbrand, campaignToPipeline, channelHealthScorecard, contentDecayMonitor, executiveGrowthReview, experimentReview, landingPageOpportunityReport, measurementQualityAudit, recommendGrowthBet } from "./tools/executive.js";
import { emailCampaignPlan, growthStrategy, keywordInsights, marketingStrategy, paidCampaignPlan, renderKeywordInsights } from "./tools/strategy.js";
import { actionHistory, approveAction, executeAction, permissionStatus, previewAction, revokeAction } from "./actions/service.js";
import type { ActionKind, ActionSource } from "./actions/types.js";

export const SERVER_VERSION="1.3.0";
export function createMarketingServer(){
const server=new McpServer({name:"general-marketing-intelligence",version:SERVER_VERSION});
const segment=z.string().min(1).optional();
const text=(value:string,data:Record<string,unknown>={})=>({content:[{type:"text" as const,text:value}],structuredContent:{markdown:value,data,meta:{serverVersion:SERVER_VERSION,generatedAt:new Date().toISOString()}}});
const liveInput={include_live_google:z.boolean().default(true),live_days:z.number().int().min(1).max(365).default(28)};
const enrich=async(value:string,include:boolean,days:number,limit=3)=>{if(!include)return {markdown:value,bundle:undefined};const bundle=await getCommercialBundle({days,rowLimit:250});return {markdown:`${value}\n\n${renderLiveOpportunities(bundle.google,limit)}\n\n${renderCommercialSignals(bundle)}`,bundle}};

server.registerTool("growth_snapshot",{title:"Growth Snapshot",description:"What changed across acquisition, and what matters commercially? Combines configured CSV context with normalized live Google evidence when available.",inputSchema:{date_range:z.string().optional().describe("Optional label for the reporting period."),segment,...liveInput}},async({segment,include_live_google,live_days})=>{const enriched=await enrich(growthSnapshot(segment),include_live_google,live_days);return text(enriched.markdown,{liveEvidence:enriched.bundle??null})});
server.registerTool("find_seo_opportunities",{title:"Find SEO Opportunities",description:"Which organic-search themes deserve a landing page, content asset or conversion improvement? Includes normalized live Google evidence when available.",inputSchema:{segment,limit:z.number().int().min(1).max(10).default(5),...liveInput}},async({segment,limit,include_live_google,live_days})=>{const enriched=await enrich(findSeoOpportunities(segment,limit),include_live_google,live_days,limit);return text(enriched.markdown,{liveEvidence:enriched.bundle??null})});
server.registerTool("audit_paid_search",{title:"Audit Paid Search",description:"Where should paid-search budget increase, decrease or pause based on SQL and pipeline quality? Uses configured CSV data.",inputSchema:{segment}},({segment})=>text(auditPaidSearch(segment)));
server.registerTool("opportunity_radar",{title:"Opportunity Radar",description:"What emerging demand should become a coordinated digital, content, field and sales motion? Combines CSV context and normalized live Google evidence.",inputSchema:{limit:z.number().int().min(1).max(5).default(3),...liveInput}},async({limit,include_live_google,live_days})=>{const enriched=await enrich(opportunityRadar(limit),include_live_google,live_days,limit),output=await enhanceMarketingOutput("Interpret why the deterministic opportunity ranking matters commercially. Preserve ranking; label any alternative interpretation.",enriched.markdown,buildEvidencePacket("opportunity_radar",{limit,include_live_google,live_days},enriched.markdown));return text(output,{liveEvidence:enriched.bundle??null})});
server.registerTool("weekly_growth_brief",{title:"Weekly Growth Brief",description:"What are the five highest-priority marketing actions for next week? Includes normalized live Google evidence.",inputSchema:{...liveInput}},async({include_live_google,live_days})=>{const enriched=await enrich(weeklyGrowthBrief(),include_live_google,live_days),output=await enhanceMarketingOutput("Synthesize a direct Head-of-Marketing weekly brief. Prioritize action and pipeline; do not change the five deterministic actions.",enriched.markdown,buildEvidencePacket("weekly_growth_brief",{include_live_google,live_days},enriched.markdown));return text(output,{liveEvidence:enriched.bundle??null})});
server.registerTool("paid_performance_review",{title:"Paid Performance Review",description:"What is happening across paid acquisition, and which signals matter commercially?",inputSchema:{}},async()=>{const fallback=paidPerformanceReview();return text(await enhanceMarketingOutput("Synthesize campaign economics into a Head-of-Marketing view. Identify misleading volume, risks and assumptions without changing calculated metrics.",fallback,buildEvidencePacket("paid_performance_review",{},fallback)))});
server.registerTool("budget_allocator",{title:"Budget Allocator",description:"Where should the next incremental marketing budget go, with reserves and guardrails?",inputSchema:{incremental_budget:z.number().positive()}},async({incremental_budget})=>{const fallback=budgetAllocator(incremental_budget);return text(await enhanceMarketingOutput("Explain the deterministic allocation, risks, assumptions, confidence and evidence that would change it. Never alter any allocation amount.",fallback,buildEvidencePacket("budget_allocator",{incremental_budget},fallback)))});
server.registerTool("design_paid_experiment",{title:"Design Paid Experiment",description:"Design a controlled paid-acquisition validation test for a segment opportunity.",inputSchema:{segment:z.string().min(1),opportunity:z.string().min(2),budget:z.number().positive().optional()}},async({segment,opportunity,budget})=>{const fallback=designPaidExperiment(segment,opportunity,budget);return text(await enhanceMarketingOutput("Improve the audience hypothesis, messaging, campaign framing and experiment design while preserving deterministic budget, thresholds and review window.",fallback,buildEvidencePacket("design_paid_experiment",{segment,opportunity,budget},fallback)))});
server.registerTool("content_strategy",{title:"Content & Category Strategy",description:"Decide what narrative and assets should support a commercial opportunity before writing them.",inputSchema:{opportunity:z.string().min(2),segment:z.string().min(2),persona:z.string().optional(),funnel_stage:z.string().optional()}},async({opportunity,segment,persona,funnel_stage})=>{const fallback=contentStrategy(opportunity,segment,persona,funnel_stage);return text(await enhanceMarketingOutput("Develop the buyer question, category narrative, content architecture, funnel role and justified field-marketing implications.",fallback,buildEvidencePacket("content_strategy",{opportunity,segment,persona,funnel_stage},fallback)))});
server.registerTool("create_campaign_asset",{title:"Create Campaign Asset Brief",description:"Create a structured, proof-safe brief for one supported commercial marketing asset.",inputSchema:{asset_type:z.enum(assetTypes),opportunity:z.string().min(2),segment:z.string().min(2),persona:z.string().optional()}},async({asset_type,opportunity,segment,persona})=>{const fallback=createCampaignAsset(asset_type,opportunity,segment,persona);return text(await enhanceMarketingOutput(`Produce a polished ${asset_type} output from the verified brief. Never invent proof; preserve placeholders.`,fallback,buildEvidencePacket("create_campaign_asset",{asset_type,opportunity,segment,persona},fallback)))});
server.registerTool("build_growth_bet",{title:"Build Growth Bet",description:"Turn the strongest opportunity or a selected segment into one coordinated, measurable marketing motion.",inputSchema:{opportunity:z.string().optional(),segment:z.string().optional(),budget:z.number().positive().optional()}},async({opportunity,segment,budget})=>{const fallback=buildGrowthBet(opportunity,segment,budget);return text(await enhanceMarketingOutput("Synthesize the strategic thesis, channel coordination, sequencing, narrative, risks and 30-day reasoning. Preserve deterministic ranking, allocation, state, confidence and metrics.",fallback,buildEvidencePacket("build_growth_bet",{opportunity,segment,budget},fallback)))});
server.registerTool("connection_status",{title:"Connection Status",description:"Truthfully report active data, AI and connector configuration.",inputSchema:{}},()=>text(connectionStatus()));
server.registerTool("diagnose_setup",{title:"Diagnose Setup",description:"Check runtime, files, property identifiers and optionally make minimal read-only Google API requests without exposing credentials.",inputSchema:{test_google_access:z.boolean().default(false)}},async({test_google_access})=>{const report=await diagnoseSetup(test_google_access);return text(report.markdown,{report})});
server.registerTool("google_search_console_report",{title:"Google Search Console Report",description:"Read filtered Search Console query/page performance with previous-period or year-over-year comparison. Returns text and structured evidence.",inputSchema:{start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),comparison:z.enum(["previous_period","year_over_year"]).default("previous_period"),country:z.string().length(3).optional(),device:z.enum(["DESKTOP","MOBILE","TABLET"]).optional(),search_type:z.enum(["web","image","video","news","discover","googleNews"]).default("web"),page_filter:z.string().max(500).optional(),query_filter:z.string().max(500).optional(),row_limit:z.number().int().min(1).max(50000).default(50)}},async(input)=>{try{const report=await searchConsoleReport({startDate:input.start_date,endDate:input.end_date,comparison:input.comparison,country:input.country,device:input.device,searchType:input.search_type,pageFilter:input.page_filter,queryFilter:input.query_filter,rowLimit:input.row_limit});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`Google Search Console request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("ga4_acquisition_report",{title:"GA4 Acquisition Report",description:"Read filtered GA4 acquisition and landing-page evidence with comparison, sampling and quota metadata.",inputSchema:{days:z.number().int().min(1).max(365).default(28),start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),comparison:z.enum(["previous_period","year_over_year"]).default("previous_period"),country:z.string().optional(),device:z.string().optional(),landing_page_filter:z.string().max(500).optional(),campaign_filter:z.string().max(500).optional(),channel_group:z.string().max(100).optional(),row_limit:z.number().int().min(1).max(10000).default(50)}},async(input)=>{try{const report=await ga4AcquisitionReport({days:input.days,startDate:input.start_date,endDate:input.end_date,comparison:input.comparison,country:input.country,device:input.device,landingPageFilter:input.landing_page_filter,campaignFilter:input.campaign_filter,channelGroup:input.channel_group,rowLimit:input.row_limit});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`GA4 request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("live_opportunity_radar",{title:"Live Opportunity Radar",description:"Normalize live GSC and GA4 evidence into deterministic segment-level validation priorities with provenance and confidence.",inputSchema:{days:z.number().int().min(1).max(365).default(28),limit:z.number().int().min(1).max(10).default(5)}},async({days,limit})=>{const bundle=await getLiveEvidence({days,rowLimit:500}),markdown=`# Live Opportunity Radar\n\n${renderLiveOpportunities(bundle,limit)}\n\n## Evidence warnings\n${bundle.warnings.map(warning=>`- ${warning}`).join("\n")}`;return text(markdown,{bundle})});
server.registerTool("save_evidence_snapshot",{title:"Save Evidence Snapshot",description:"Explicitly fetch normalized live Google evidence and save a private local metric snapshot for historical comparison.",inputSchema:{days:z.number().int().min(1).max(365).default(28)}},async({days})=>{const bundle=await getLiveEvidence({days,rowLimit:500}),path=saveSnapshot(bundle),markdown=`# Evidence snapshot saved\n\n**Path:** ${path}  \n**Evidence records:** ${bundle.evidence.length}  \n**Opportunities:** ${bundle.opportunities.length}\n\nThe snapshot contains metrics and provenance, never Google credential contents.`;return text(markdown,{path,bundle})});
server.registerTool("snapshot_history",{title:"Snapshot History",description:"List locally stored normalized evidence snapshots without contacting external APIs.",inputSchema:{limit:z.number().int().min(1).max(50).default(10)}},({limit})=>{const snapshots=listSnapshots(limit),markdown=`# Snapshot history\n\n${snapshots.length?snapshots.map(row=>`- ${row.generatedAt} — ${row.evidenceCount} evidence records, ${row.opportunityCount} opportunities (${row.file})`).join("\n"):"No snapshots have been saved."}`;return text(markdown,{snapshots})});

const reportDates={start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),row_limit:z.number().int().min(1).max(10000).default(100)};
server.registerTool("google_ads_report",{title:"Google Ads Report",description:"Run one predefined read-only GAQL report for campaign, ad-group, search-term, landing-page, device or geography evidence.",inputSchema:{view:z.enum(["campaign","ad_group","search_term","landing_page","geography"]).default("campaign"),...reportDates,campaign_filter:z.string().max(100).optional()}},async({view,start_date,end_date,row_limit,campaign_filter})=>{try{const report=await googleAdsReport({view,startDate:start_date,endDate:end_date,rowLimit:row_limit,campaignFilter:campaign_filter});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`Google Ads request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("hubspot_funnel_report",{title:"HubSpot Funnel Report",description:"Read and aggregate HubSpot contact lifecycle and deal pipeline evidence. Never writes CRM records.",inputSchema:reportDates},async({start_date,end_date,row_limit})=>{try{const report=await hubspotFunnelReport({startDate:start_date,endDate:end_date,rowLimit:row_limit});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`HubSpot request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("salesforce_funnel_report",{title:"Salesforce Funnel Report",description:"Read and aggregate Salesforce lead and opportunity evidence through SOQL. Never writes CRM records.",inputSchema:reportDates},async({start_date,end_date,row_limit})=>{try{const report=await salesforceFunnelReport({startDate:start_date,endDate:end_date,rowLimit:row_limit});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`Salesforce request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("generic_crm_csv_report",{title:"Generic CRM CSV Report",description:"Validate and aggregate a vendor-neutral CRM funnel CSV contract.",inputSchema:{...reportDates,path:z.string().optional()}},({start_date,end_date,row_limit,path})=>{try{const report=genericCrmCsvReport({path,startDate:start_date,endDate:end_date,rowLimit:row_limit});return text(report.markdown,{report})}catch(error){return {content:[{type:"text" as const,text:`CRM CSV request failed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("connector_catalog",{title:"Connector Catalog",description:"List implemented and planned connectors sharing the read-only normalization contract.",inputSchema:{}},()=>text(`# Connector Catalog\n\n${connectorCatalog.map(row=>`- **${row.label}** — ${row.status}, ${row.mode}, ${row.category}`).join("\n")}`,{connectors:connectorCatalog}));

const commercialInput={days:z.number().int().min(1).max(365).default(28),row_limit:z.number().int().min(1).max(2000).default(500)};
server.registerTool("executive_growth_review",{title:"Executive Growth Review",description:"Prioritize commercially meaningful evidence across search, web behavior, paid cost and CRM outcomes.",inputSchema:commercialInput},async({days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(executiveGrowthReview(bundle),{bundle})});
server.registerTool("channel_health_scorecard",{title:"Channel Health Scorecard",description:"Classify channels by traffic, platform conversion and CRM evidence without conflating them.",inputSchema:commercialInput},async({days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(channelHealthScorecard(bundle),{bundle})});
server.registerTool("landing_page_opportunity_report",{title:"Landing Page Opportunity Report",description:"Join normalized GSC and GA4 landing-page evidence and classify the next action.",inputSchema:{...commercialInput,limit:z.number().int().min(1).max(100).default(20)}},async({days,row_limit,limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit,includeGoogleAds:false,includeCrm:false});return text(landingPageOpportunityReport(bundle,limit),{bundle})});
server.registerTool("brand_vs_nonbrand_search",{title:"Brand vs Non-brand Search",description:"Classify live GSC queries using explicit brand terms and compare demand and CTR.",inputSchema:{brand_terms:z.array(z.string().min(1)).min(1),days:z.number().int().min(1).max(365).default(28),row_limit:z.number().int().min(1).max(50000).default(1000)}},async({brand_terms,days,row_limit})=>{const dates=new Date(Date.now()-86400000),end=dates.toISOString().slice(0,10),start=new Date(dates.getTime()-(days-1)*86400000).toISOString().slice(0,10),report=await searchConsoleReport({startDate:start,endDate:end,rowLimit:row_limit});return text(brandVsNonbrand(report,brand_terms),{report,brandTerms:brand_terms})});
server.registerTool("content_decay_monitor",{title:"Content Decay Monitor",description:"Compare the two latest local evidence snapshots and surface declining query/page demand.",inputSchema:{limit:z.number().int().min(1).max(100).default(20)}},({limit})=>text(contentDecayMonitor(limit)));
server.registerTool("campaign_to_pipeline_report",{title:"Campaign-to-Pipeline Report",description:"Compare Google Ads cost and conversions with CRM pipeline and revenue using explicit campaign matching.",inputSchema:commercialInput},async({days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(campaignToPipeline(bundle),{bundle})});
server.registerTool("measurement_quality_audit",{title:"Measurement Quality Audit",description:"Identify missing acquisition, behavior, paid, CRM, mapping and historical evidence.",inputSchema:commercialInput},async({days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(measurementQualityAudit(bundle),{bundle})});
server.registerTool("experiment_review",{title:"Experiment Review",description:"Calculate conversion-efficiency and pipeline changes against an explicit success threshold.",inputSchema:{name:z.string().min(1),baseline_spend:z.number().nonnegative().optional(),current_spend:z.number().nonnegative().optional(),baseline_conversions:z.number().nonnegative().optional(),current_conversions:z.number().nonnegative().optional(),baseline_pipeline:z.number().nonnegative().optional(),current_pipeline:z.number().nonnegative().optional(),success_threshold:z.number().min(-1).max(10).default(.1)}},input=>text(experimentReview({name:input.name,baselineSpend:input.baseline_spend,currentSpend:input.current_spend,baselineConversions:input.baseline_conversions,currentConversions:input.current_conversions,baselinePipeline:input.baseline_pipeline,currentPipeline:input.current_pipeline,successThreshold:input.success_threshold}),{inputs:input}));
server.registerTool("recommend_next_growth_bet",{title:"Recommend Next Growth Bet",description:"Rank normalized evidence with CRM outcomes weighted above platform conversions and traffic.",inputSchema:commercialInput},async({days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(recommendGrowthBet(bundle),{bundle})});

server.registerTool("keyword_opportunity_research",{title:"Keyword Opportunity Research",description:"Classify and rank observed GSC queries by length, intent and SEO/SEM opportunity; optionally joins configured Google Ads search-term evidence.",inputSchema:{days:z.number().int().min(1).max(365).default(28),brand_terms:z.array(z.string().min(1)).default([]),limit:z.number().int().min(1).max(100).default(25)}},async({days,brand_terms,limit})=>{const endDate=new Date(Date.now()-86400000),end=endDate.toISOString().slice(0,10),start=new Date(endDate.getTime()-(days-1)*86400000).toISOString().slice(0,10),search=await searchConsoleReport({startDate:start,endDate:end,rowLimit:Math.max(500,limit*10)});let paidRows:Awaited<ReturnType<typeof googleAdsReport>>["rows"]=[],paidWarning="Google Ads search-term evidence was not configured or available.";try{const paid=await googleAdsReport({view:"search_term",rowLimit:1000});paidRows=paid.rows;paidWarning="Google Ads search-term evidence was joined by normalized literal query."}catch{}const rows=keywordInsights(search.rows,paidRows,brand_terms,limit),warnings=[...search.meta.warnings,paidWarning,"Keyword Planner and total market search volume are not connected in this release."];return text(renderKeywordInsights(rows,warnings),{rows,warnings,period:{days,startDate:start,endDate:end}})});
server.registerTool("derive_growth_strategy",{title:"Derive Growth Strategy",description:"Create a growth-system recommendation across acquisition, activation, commercial validation and experiments from configured evidence.",inputSchema:{objective:z.string().min(3),horizon_days:z.number().int().min(7).max(365).default(30),...commercialInput}},async({objective,horizon_days,days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(growthStrategy(bundle,objective,horizon_days),{bundle,objective,horizonDays:horizon_days})});
server.registerTool("derive_marketing_strategy",{title:"Derive Marketing Strategy",description:"Create a distinct audience, positioning, demand creation, demand capture and measurement strategy from configured evidence.",inputSchema:{audience:z.string().min(2),positioning_hypothesis:z.string().min(3),horizon_days:z.number().int().min(7).max(365).default(30),...commercialInput}},async({audience,positioning_hypothesis,horizon_days,days,row_limit})=>{const bundle=await getCommercialBundle({days,rowLimit:row_limit});return text(marketingStrategy(bundle,audience,positioning_hypothesis,horizon_days),{bundle,audience,positioningHypothesis:positioning_hypothesis,horizonDays:horizon_days})});
server.registerTool("build_paid_campaign_plan",{title:"Build Paid Campaign Plan",description:"Build a deterministic paid-search draft only. It never creates or changes an advertising campaign.",inputSchema:{name:z.string().min(2),objective:z.string().min(3),audience:z.string().min(2),offer:z.string().min(2),landing_page:z.string().url(),budget:z.number().positive(),keywords:z.array(z.string().min(1)).min(1).max(100),match_types:z.array(z.enum(["exact","phrase","broad"])).min(1).default(["exact","phrase"])}},input=>{const plan=paidCampaignPlan({name:input.name,objective:input.objective,audience:input.audience,offer:input.offer,landingPage:input.landing_page,budget:input.budget,keywords:input.keywords,matchTypes:input.match_types});return text(`# Paid Campaign Plan\n\n**Status:** DRAFT, NOT EXECUTED  \n**Campaign:** ${plan.name}  \n**Budget cap:** ${plan.budget.toFixed(2)}  \n**Landing page:** ${plan.landingPage}\n\n## Ad groups\n${plan.adGroups.map(group=>`- **${group.theme}:** ${group.keywords.map(row=>`[${row.matchType}] ${row.keyword}`).join(", ")}`).join("\n")}\n\n## Controls\n- Negative-keyword review required\n- Conversion goal must be explicitly configured\n- ${plan.stopCondition}\n- Use the approval tools only if you want to save this draft or a future write adapter is enabled.`,{plan})});
server.registerTool("build_email_campaign_plan",{title:"Build Email Campaign Plan",description:"Build a deterministic email sequence and compliance checklist. It never sends email.",inputSchema:{name:z.string().min(2),objective:z.string().min(3),audience:z.string().min(2),offer:z.string().min(2),audience_size:z.number().int().nonnegative(),cta:z.string().min(2)}},input=>{const plan=emailCampaignPlan({name:input.name,objective:input.objective,audience:input.audience,offer:input.offer,emails:input.audience_size,cta:input.cta});return text(`# Email Campaign Plan\n\n**Status:** DRAFT, NOT SENT  \n**Campaign:** ${plan.name}  \n**Audience:** ${plan.audience} (${plan.audienceSize} recipients)  \n**CTA:** ${plan.cta}\n\n## Sequence\n${plan.sequence.map((step,index)=>`${index+1}. ${step}`).join("\n")}\n\n## Required checks\n${plan.requiredChecks.map(check=>`- ${check}`).join("\n")}`,{plan})});

const actionKinds=["save_campaign_draft","create_paid_campaign","update_campaign_budget","pause_campaign","create_crm_campaign","send_email_campaign"] as const,actionSources=["local_artifacts","google_ads","hubspot","salesforce","email"] as const;
server.registerTool("action_permission_status",{title:"Action Permission Status",description:"Show the active read, draft and write policy without exposing credentials.",inputSchema:{}},()=>{const policy=permissionStatus();return text(`# Action Permission Status\n\n**Mode:** ${policy.mode}\n**Approval TTL:** ${policy.approvalTtlMinutes} minutes\n\n${Object.entries(policy.sources).map(([source,value])=>`- **${source}:** read=${value?.read}, draft=${value?.draft}, write=${value?.write}`).join("\n")}\n\n${policy.guarantees.map(value=>`- ${value}`).join("\n")}`,{policy})});
server.registerTool("preview_marketing_action",{title:"Preview Marketing Action",description:"Create an immutable, expiring preview of an exact action. This does not approve or execute it.",inputSchema:{kind:z.enum(actionKinds),source:z.enum(actionSources),summary:z.string().min(5),payload:z.record(z.unknown()),risk:z.enum(["low","medium","high"]),expected_state:z.record(z.unknown()).optional()}},input=>{const preview=previewAction({kind:input.kind as ActionKind,source:input.source as ActionSource,summary:input.summary,payload:input.payload,risk:input.risk,expectedState:input.expected_state});return text(`# Marketing Action Preview\n\n**Approval ID:** ${preview.approvalId}  \n**Expires:** ${preview.expiresAt}  \n**Risk:** ${preview.request.risk.toUpperCase()}  \n**Summary:** ${preview.request.summary}\n\n## Exact payload\n\n\`\`\`json\n${JSON.stringify(preview.request.payload,null,2)}\n\`\`\`\n\nThis action has not been approved or executed. Claude or Codex must show this preview to the user and ask them to type **APPROVE ${preview.approvalId}** before calling the approval tool.`,{preview})});
server.registerTool("approve_marketing_action",{title:"Approve Marketing Action",description:"Record a human's exact approval. Claude or Codex MUST NOT call this unless the user explicitly typed the exact APPROVE phrase shown by preview_marketing_action.",inputSchema:{approval_id:z.string().regex(/^apr_[0-9a-f-]{36}$/),confirmation:z.string()}},({approval_id,confirmation})=>{const approval=approveAction(approval_id,confirmation);return text(`# Approval Recorded\n\n**Approval ID:** ${approval.approvalId}  \n**Status:** APPROVED  \n**Expires:** ${approval.expiresAt}\n\nNothing has executed yet. Claude or Codex must ask separately whether to execute this approved action now.`,{approval})});
server.registerTool("execute_approved_action",{title:"Execute Approved Marketing Action",description:"Execute one previously approved exact action. Never call before preview and explicit human approval. External platform adapters remain disabled in this release.",inputSchema:{approval_id:z.string().regex(/^apr_[0-9a-f-]{36}$/)}},async({approval_id})=>{try{const result=await executeAction(approval_id);return text(`# Approved Action Executed\n\n**Approval ID:** ${approval_id}  \n**Result:** ${JSON.stringify(result)}\n\nThe action was bounded to the approved payload and recorded in the audit history.`,{result})}catch(error){return {content:[{type:"text" as const,text:`Approved action was not executed: ${error instanceof Error?error.message:"Unknown error"}`}],isError:true}}});
server.registerTool("revoke_action_approval",{title:"Revoke Action Approval",description:"Revoke a pending preview or approval before it executes.",inputSchema:{approval_id:z.string().regex(/^apr_[0-9a-f-]{36}$/)}},({approval_id})=>{const approval=revokeAction(approval_id);return text(`# Approval Revoked\n\n**Approval ID:** ${approval.approvalId}  \n**Status:** REVOKED`,{approval})});
server.registerTool("action_audit_history",{title:"Action Audit History",description:"List local action lifecycle metadata without returning credential contents or full marketing payloads.",inputSchema:{limit:z.number().int().min(1).max(100).default(20)}},({limit})=>{const records=actionHistory(limit);return text(`# Action Audit History\n\n${records.map(record=>`- ${record.createdAt} | ${record.approvalId} | ${record.kind} | ${record.status} | ${record.summary}`).join("\n")||"No action records."}`,{records})});

return server;
}
