import { completedDateWindow } from "../connectors/google/dates.js";
import { googleAdsReport, googleAdsEvidenceId, type GoogleAdsReport } from "../connectors/google/googleAds.js";
import { hubspotFunnelReport } from "../connectors/crm/hubspot.js";
import { salesforceFunnelReport } from "../connectors/crm/salesforce.js";
import { genericCrmCsvReport } from "../connectors/crm/csv.js";
import type { CrmReport } from "../connectors/crm/types.js";
import { getLiveEvidence } from "./live.js";
import { loadMappingConfig, mapSegment } from "./mapping.js";
import type { EvidenceBundle, NormalizedEvidence } from "./schema.js";
export interface CommercialBundle {google:EvidenceBundle;googleAds?:GoogleAdsReport;crm?:CrmReport;evidence:NormalizedEvidence[];warnings:string[]}
const crmProvider=()=>{const requested=(process.env.CRM_PROVIDER??"auto").toLowerCase();if(requested!=="auto")return requested;if(process.env.HUBSPOT_ACCESS_TOKEN)return "hubspot";if(process.env.SALESFORCE_ACCESS_TOKEN)return "salesforce";if(process.env.GENERIC_CRM_CSV)return "csv";return "none"};
export async function getCommercialBundle(input:{days?:number;rowLimit?:number;includeGoogleAds?:boolean;includeCrm?:boolean}={}):Promise<CommercialBundle>{
 const days=input.days??28,rowLimit=input.rowLimit??500,dates=completedDateWindow(undefined,undefined,days),google=await getLiveEvidence({days,rowLimit}),mapping=loadMappingConfig(),warnings=[...google.warnings];let ads:GoogleAdsReport|undefined,crm:CrmReport|undefined;
 if(input.includeGoogleAds!==false&&process.env.GOOGLE_ADS_CUSTOMER_ID)try{ads=await googleAdsReport({view:"campaign",startDate:dates.startDate,endDate:dates.endDate,rowLimit});}catch(error){warnings.push(`Google Ads unavailable: ${error instanceof Error?error.message:"Unknown error"}`)}
 if(input.includeCrm!==false)try{const provider=crmProvider();crm=provider==="hubspot"?await hubspotFunnelReport({startDate:dates.startDate,endDate:dates.endDate,rowLimit}):provider==="salesforce"?await salesforceFunnelReport({startDate:dates.startDate,endDate:dates.endDate,rowLimit}):provider==="csv"?genericCrmCsvReport({startDate:dates.startDate,endDate:dates.endDate,rowLimit}):undefined}catch(error){warnings.push(`CRM unavailable: ${error instanceof Error?error.message:"Unknown error"}`)}
 const evidence=[...google.evidence];for(const row of ads?.rows??[]){const mapped=mapSegment({campaign:row.campaign,landingPage:row.landingPage},mapping);evidence.push({id:googleAdsEvidenceId([ads?.meta.customerId,ads?.meta.startDate,row.view,row.campaign,row.dimension]),source:"google_ads",property:ads!.meta.customerId,period:{startDate:ads!.meta.startDate,endDate:ads!.meta.endDate},retrievedAt:ads!.meta.retrievedAt,...mapped,campaign:row.campaign,landingPage:row.landingPage,metrics:{impressions:row.impressions,clicks:row.clicks,spend:row.spend,conversions:row.conversions,conversionValue:row.conversionValue,impressionShare:row.impressionShare??undefined,lostImpressionShare:row.lostImpressionShare??undefined},provenance:{method:"Google Ads GAQL read-only report; cost micros converted in TypeScript",limitations:ads!.meta.warnings}})}
 for(const row of crm?.rows??[]){const mapped=row.segment&&row.segment!=="Unmapped"?{segment:row.segment,mapping:"configured" as const}:mapSegment({campaign:row.campaign},mapping);evidence.push({id:googleAdsEvidenceId([row.source,row.recordType,row.recordId]),source:row.source,property:row.source,period:{startDate:crm!.meta.startDate,endDate:crm!.meta.endDate},retrievedAt:crm!.meta.retrievedAt,...mapped,campaign:row.campaign,sourceMedium:row.latestTouchSource,metrics:{leads:row.recordType!=="opportunity"?1:0,mqls:/marketingqualifiedlead|mql/i.test(row.lifecycleStage)?1:0,sqls:/salesqualifiedlead|sql/i.test(row.lifecycleStage)?1:0,opportunities:row.recordType==="opportunity"?1:0,pipeline:row.pipelineValue,revenue:row.closedWonRevenue},provenance:{method:`${row.source} read-only funnel record normalized in TypeScript`,limitations:crm!.meta.warnings}})}
 return {google,googleAds:ads,crm,evidence,warnings};
}
export function renderCommercialSignals(bundle:CommercialBundle):string {const ads=bundle.googleAds?.rows??[],crm=bundle.crm,spend=ads.reduce((sum,row)=>sum+row.spend,0),conversions=ads.reduce((sum,row)=>sum+row.conversions,0);return `## Commercial evidence\n\n| Evidence | Result |\n|---|---:|\n| Google Ads spend | ${bundle.googleAds?spend.toFixed(2):"Not connected"} |\n| Google Ads configured conversions | ${bundle.googleAds?conversions.toFixed(2):"Not connected"} |\n| CRM MQLs / SQLs | ${crm?`${crm.summary.mqls} / ${crm.summary.sqls}`:"Not connected"} |\n| CRM opportunities | ${crm?crm.summary.opportunities:"Not connected"} |\n| CRM open pipeline | ${crm?crm.summary.pipeline.toFixed(2):"Not connected"} |\n| CRM closed-won revenue | ${crm?crm.summary.closedWonRevenue.toFixed(2):"Not connected"} |\n\nPlatform conversions are not treated as CRM pipeline. All connector access is read-only.`}
