import { createHash } from "node:crypto";
import type { Ga4Report, SearchConsoleReport } from "../connectors/google/types.js";
import { loadMappingConfig, mapSegment, type MappingConfig } from "./mapping.js";
import type { EvidenceBundle, LiveOpportunity, NormalizedEvidence } from "./schema.js";
const id=(parts:unknown[])=>createHash("sha256").update(JSON.stringify(parts)).digest("hex").slice(0,16);
const sum=(rows:NormalizedEvidence[],key:keyof NormalizedEvidence["metrics"])=>rows.reduce((total,row)=>total+(typeof row.metrics[key]==="number"?Number(row.metrics[key]):0),0);
const weightedGrowth=(rows:NormalizedEvidence[])=>{const eligible=rows.filter(row=>typeof row.metrics.impressionGrowth==="number"&&(row.metrics.previousImpressions??0)>0),weight=sum(eligible,"previousImpressions");return weight?eligible.reduce((total,row)=>total+Number(row.metrics.impressionGrowth)*(row.metrics.previousImpressions??0),0)/weight:null};

export function normalizeGoogleEvidence(gsc:SearchConsoleReport|undefined,ga4:Ga4Report|undefined,config:MappingConfig=loadMappingConfig()):EvidenceBundle{
 const evidence:NormalizedEvidence[]=[];
 if(gsc)for(const row of gsc.rows){const mapped=mapSegment({query:row.query,landingPage:row.page},config);evidence.push({id:id(["gsc",gsc.meta.property,gsc.meta.startDate,row.query,row.page]),source:"google_search_console",property:gsc.meta.property,period:{startDate:gsc.meta.startDate,endDate:gsc.meta.endDate},retrievedAt:gsc.meta.retrievedAt,...mapped,query:row.query,landingPage:row.page,metrics:{impressions:row.impressions,clicks:row.clicks,ctr:row.ctr,position:row.position,previousImpressions:row.previousImpressions,impressionGrowth:row.impressionGrowth},provenance:{method:"Search Console query/page API; comparison calculated in TypeScript",limitations:gsc.meta.warnings}})}
 if(ga4)for(const row of ga4.rows){const mapped=mapSegment({landingPage:row.landingPage,campaign:row.campaign},config);evidence.push({id:id(["ga4",ga4.meta.property,ga4.meta.startDate,row.sourceMedium,row.campaign,row.landingPage]),source:"ga4",property:ga4.meta.property,period:{startDate:ga4.meta.startDate,endDate:ga4.meta.endDate},retrievedAt:ga4.meta.retrievedAt,...mapped,landingPage:row.landingPage,campaign:row.campaign,sourceMedium:row.sourceMedium,metrics:{sessions:row.sessions,users:row.users,keyEvents:row.keyEvents,keyEventsPerSession:row.keyEventsPerSession,revenue:row.revenue},provenance:{method:"GA4 Data API; ratios calculated in TypeScript",limitations:ga4.meta.warnings}})}
 const segments=[...new Set(evidence.map(row=>row.segment))],opportunities:LiveOpportunity[]=segments.map(segment=>{const rows=evidence.filter(row=>row.segment===segment),gscRows=rows.filter(row=>row.source==="google_search_console"),gaRows=rows.filter(row=>row.source==="ga4"),impressions=sum(gscRows,"impressions"),clicks=sum(gscRows,"clicks"),sessions=sum(gaRows,"sessions"),keyEvents=sum(gaRows,"keyEvents"),revenue=sum(gaRows,"revenue"),growth=weightedGrowth(gscRows),configured=rows.some(row=>row.mapping==="configured"),both=gscRows.length>0&&gaRows.length>0,score=Math.min(100,Math.log10(impressions+1)*10+Math.max(0,growth??0)*20+Math.log10(sessions+1)*8+Math.min(keyEvents/Math.max(sessions,1)*100,20)),state=keyEvents>=5&&both?"ACCELERATE" as const:both?"VALIDATE" as const:"MONITOR" as const,confidence=both&&configured?"HIGH" as const:both?"MEDIUM" as const:"LOW" as const;return {segment,score:Number(score.toFixed(2)),state,confidence,impressions,clicks,sessions,keyEvents,revenue,demandGrowth:growth,signal:`${impressions} search impressions, ${clicks} organic clicks, ${sessions} GA4 sessions and ${keyEvents} key events in the selected period.`,hypothesis:both?"Search demand and on-site behavior may represent the same buyer opportunity; mapping quality determines confidence.":"Only one live Google evidence family is present, so commercial validation is incomplete.",recommendedAction:state==="ACCELERATE"?"Run a controlled conversion test and validate downstream pipeline before scaling.":state==="VALIDATE"?"Validate query-to-landing-page intent and key-event quality before investment.":"Complete source mapping and collect conversion evidence.",evidenceIds:rows.map(row=>row.id)}}).sort((a,b)=>b.score-a.score);
 return {generatedAt:new Date().toISOString(),mappingVersion:config.version,evidence,opportunities,warnings:[...(gsc?.meta.warnings??[]),...(ga4?.meta.warnings??[]),...(config.segments.length?[]:["No MARKETING_MAPPING_FILE is configured; URL-path inference is used and confidence is limited."])]};
}

export function renderLiveOpportunities(bundle:EvidenceBundle,limit=3):string{
 const rows=bundle.opportunities.slice(0,limit);return `## Live Google evidence\n\n${rows.length?rows.map((row,index)=>`### ${index+1}. ${row.segment} — ${row.state} (${row.confidence} confidence)\n\n**Code-calculated score:** ${row.score}/100  \n**Signal:** ${row.signal}  \n**Demand growth:** ${row.demandGrowth===null?"Unavailable":`${(row.demandGrowth*100).toFixed(1)}%`}  \n**Hypothesis:** ${row.hypothesis}  \n**Recommended action:** ${row.recommendedAction}`).join("\n\n"):"No normalized live evidence is available."}\n\n> Live Google evidence does not include CRM pipeline. Scores rank validation priority; they do not prove causality or revenue impact.`;
}
