import { disclaimer } from "../analysis/metrics.js";
export const assetTypes=["landing_page","executive_social_post","webinar_brief","executive_roundtable_brief","sales_enablement"] as const;
export type AssetType=typeof assetTypes[number];
const persona=(value?:string)=>value??"Primary decision-maker for the selected segment";
export function contentStrategy(opportunity:string,segment:string,buyer?:string,funnelStage?:string):string {
 const p=persona(buyer);
 return `# Content Strategy — ${opportunity}\n\n> ${disclaimer}\n\n**Segment:** ${segment}  \n**Target persona:** ${p}  \n**Buyer problem:** define the operational or commercial problem using customer evidence before publication.  \n**Buyer question:** why should this buyer act now, and what verified evidence reduces decision risk?  \n**Funnel context:** ${funnelStage??"Evaluation and demand capture"}\n\n## Narrative\n\n**Core message:** connect ${opportunity} to the outcome the buyer owns.  \n**Proof rule:** use [Insert verified evidence] for every unverified customer, product or market claim.\n\n## Content architecture\n\n| Role | Asset | Commercial job | Success metric |\n|---|---|---|---|\n| Demand capture | Dedicated landing page | Convert high-intent demand | SQLs and pipeline |\n| Buyer education | Evaluation guide | Define decision criteria | Target-account progression |\n| Executive POV | Evidence-led social post | Shape the problem | Relevant inbound |\n| Proof | Verified case study | Reduce purchase risk | Demo-to-SQL conversion |\n| Field | Small peer session when justified | Create qualified conversations | Meetings and opportunities |\n| Sales | Discovery and objection guide | Improve follow-up | Opportunity progression |`;
}
export function createCampaignAsset(type:AssetType,opportunity:string,segment:string,buyer?:string):string {
 const p=persona(buyer),common=`> ${disclaimer}\n\n**Opportunity:** ${opportunity}  \n**Segment:** ${segment}  \n**Persona:** ${p}  \n**Proof policy:** replace every placeholder with verified evidence before use.`;
 if(type==="landing_page")return `# Landing Page Brief — ${opportunity}\n\n${common}\n\n**Headline:** Connect ${opportunity} to a measurable business outcome  \n**Buyer problem:** [Insert verified buyer problem]  \n**Approach:** explain the workflow, controls, implementation and outcome measurement.  \n**Proof:** [Insert verified customer result]; [Insert verified product capability].  \n**Primary CTA:** Choose the next step appropriate to the funnel.  \n**Success metric:** visitor-to-SQL conversion and sourced pipeline.`;
 if(type==="executive_roundtable_brief")return `# Executive Roundtable Brief — ${opportunity}\n\n${common}\n\n**Executive question:** What must change for ${opportunity} to create a measurable business outcome?  \n**Format:** 12–18 invited peers; facilitated discussion, not a product pitch.  \n**Agenda:** current constraint → success definition → implementation lessons → next practices.  \n**Follow-up:** permission-based insight memo and relevant next step.  \n**Success metric:** qualified accounts, meetings, opportunities and pipeline.`;
 if(type==="webinar_brief")return `# Webinar Brief — ${opportunity}\n\n${common}\n\n**Title:** An operator's guide to ${opportunity}  \n**Thesis:** give the buyer a practical evaluation framework.  \n**Sections:** problem; decision criteria; implementation; measurement; verified example.  \n**Guest:** practitioner with verifiable experience.  \n**Success metric:** qualified registrations, attendance, meetings and pipeline.`;
 if(type==="executive_social_post")return `# Executive Social Post Brief — ${opportunity}\n\n${common}\n\n**Hook:** challenge a common input metric or assumption.  \n**Point of view:** connect the issue to the outcome the buyer owns.  \n**Evidence:** [Insert verified evidence].  \n**Conversation CTA:** ask peers how they evaluate the decision.  \n**Success metric:** relevant engagement and inbound from target accounts.`;
 return `# Sales Enablement Brief — ${opportunity}\n\n${common}\n\n**Positioning:** outcome-led ${opportunity} for ${segment}.  \n**Discovery:** current process; cost of the problem; success metric; constraints; decision process.  \n**Objections:** proof, priority, implementation, risk and economics.  \n**Required proof:** [Insert verified customer result]; [Insert verified capability]; [Insert verified commercial evidence].  \n**Next step:** scoped discovery or evaluation workshop.  \n**Success metric:** qualified progression and pipeline.`;
}
