import { accessSync, constants, existsSync, readFileSync } from "node:fs";
import { ga4AcquisitionReport } from "../connectors/google/ga4.js";
import { searchConsoleReport } from "../connectors/google/searchConsole.js";
import { dataMode, localDataReady } from "../connectors/config.js";
import { googleAdsReport } from "../connectors/google/googleAds.js";
import { hubspotFunnelReport } from "../connectors/crm/hubspot.js";
import { salesforceFunnelReport } from "../connectors/crm/salesforce.js";
import { genericCrmCsvReport } from "../connectors/crm/csv.js";
export type DiagnosticState="PASS"|"WARN"|"FAIL"|"SKIP";
export interface DiagnosticCheck {name:string;state:DiagnosticState;detail:string;fix?:string}
export interface DiagnosticReport {generatedAt:string;healthy:boolean;checks:DiagnosticCheck[];markdown:string}
const checkCredential=():DiagnosticCheck=>{const path=process.env.GOOGLE_APPLICATION_CREDENTIALS;if(!path&&!process.env.GSC_SITE_URL&&!process.env.GA4_PROPERTY_ID)return {name:"Google credential file",state:"SKIP",detail:"GSC and GA4 are not configured."};if(!path)return {name:"Google credential file",state:"FAIL",detail:"GOOGLE_APPLICATION_CREDENTIALS is missing.",fix:"Add an absolute path to a service-account JSON file in the MCP client environment."};if(!existsSync(path))return {name:"Google credential file",state:"FAIL",detail:"The configured credential file does not exist.",fix:"Correct the absolute path; do not paste credential contents into configuration."};try{accessSync(path,constants.R_OK);const parsed=JSON.parse(readFileSync(path,"utf8")) as {type?:string;client_email?:string;private_key?:string};if(parsed.type!=="service_account"||!parsed.client_email||!parsed.private_key)return {name:"Google credential file",state:"FAIL",detail:"The file is readable but is not a complete service-account credential.",fix:"Download a JSON key for the intended service account."};return {name:"Google credential file",state:"PASS",detail:`Readable service-account credential for ${parsed.client_email}.`}}catch{return {name:"Google credential file",state:"FAIL",detail:"The configured credential file is unreadable or invalid JSON.",fix:"Check file permissions and download a fresh JSON key if necessary."}}};
export async function diagnoseSetup(testGoogleAccess=false):Promise<DiagnosticReport>{
 const adsKeys=["GOOGLE_ADS_CUSTOMER_ID","GOOGLE_ADS_DEVELOPER_TOKEN","GOOGLE_ADS_CLIENT_ID","GOOGLE_ADS_CLIENT_SECRET","GOOGLE_ADS_REFRESH_TOKEN"],adsCount=adsKeys.filter(key=>process.env[key]).length,crmConfigured=Boolean(process.env.HUBSPOT_ACCESS_TOKEN||process.env.SALESFORCE_ACCESS_TOKEN||process.env.GENERIC_CRM_CSV),checks:DiagnosticCheck[]=[{name:"Runtime",state:Number(process.versions.node.split(".")[0])>=20?"PASS":"FAIL",detail:`Node.js ${process.versions.node}; version 20 or 22 is supported.`},{name:"Cross-channel data",state:process.env.DATA_MODE==="local"&&!localDataReady()?"WARN":"PASS",detail:`Effective mode: ${dataMode()}.`,fix:process.env.DATA_MODE==="local"&&!localDataReady()?"Import all three CSV files or use DATA_MODE=demo.":undefined},checkCredential(),{name:"Search Console property",state:process.env.GSC_SITE_URL?"PASS":"SKIP",detail:process.env.GSC_SITE_URL?`Configured as ${process.env.GSC_SITE_URL}.`:"Not configured.",fix:undefined},{name:"GA4 property",state:!process.env.GA4_PROPERTY_ID?"SKIP":/^\d+$/.test(process.env.GA4_PROPERTY_ID)?"PASS":"FAIL",detail:process.env.GA4_PROPERTY_ID?"A GA4 property identifier is configured.":"Not configured.",fix:process.env.GA4_PROPERTY_ID&&!/^\d+$/.test(process.env.GA4_PROPERTY_ID)?"Use the numeric Property ID, not the G- measurement ID.":undefined},{name:"Google Ads configuration",state:adsCount===0?"SKIP":adsCount===adsKeys.length?"PASS":"WARN",detail:adsCount===0?"Not configured.":`${adsCount}/${adsKeys.length} required variables are present.`,fix:adsCount>0&&adsCount<adsKeys.length?"Complete all Google Ads OAuth and developer-token variables.":undefined},{name:"CRM configuration",state:crmConfigured?"PASS":"SKIP",detail:crmConfigured?"At least one read-only CRM source is configured.":"HubSpot, Salesforce and generic CRM CSV are not configured."}];
 if(testGoogleAccess){const tests:Array<[string,()=>Promise<unknown>|unknown]>=[["Search Console API",()=>searchConsoleReport({rowLimit:1})],["GA4 Data API",()=>ga4AcquisitionReport({days:7,rowLimit:1})]];if(adsCount===adsKeys.length)tests.push(["Google Ads API",()=>googleAdsReport({view:"campaign",rowLimit:1})]);if(process.env.HUBSPOT_ACCESS_TOKEN)tests.push(["HubSpot API",()=>hubspotFunnelReport({rowLimit:1})]);if(process.env.SALESFORCE_ACCESS_TOKEN)tests.push(["Salesforce API",()=>salesforceFunnelReport({rowLimit:1})]);if(process.env.GENERIC_CRM_CSV)tests.push(["Generic CRM CSV",()=>genericCrmCsvReport({rowLimit:1})]);for(const [name,run] of tests){try{await run();checks.push({name,state:"PASS",detail:"Read-only request succeeded."})}catch(error){checks.push({name,state:"FAIL",detail:error instanceof Error?error.message:"Unknown error",fix:"Check API enablement, property identifier, token scopes and product permissions."})}}}else checks.push({name:"Live API access",state:"SKIP",detail:"Set test_google_access=true to perform minimal read-only requests for configured connectors."});
 const healthy=!checks.some(check=>check.state==="FAIL"),markdown=`# Setup diagnostics\n\n**Overall:** ${healthy?"READY":"NEEDS ATTENTION"}  \n**Generated:** ${new Date().toISOString()}\n\n${checks.map(check=>`- **${check.state} — ${check.name}:** ${check.detail}${check.fix?` Fix: ${check.fix}`:""}`).join("\n")}\n\nNo credential values are included in this report.`;return {generatedAt:new Date().toISOString(),healthy,checks,markdown};
}
