import { data } from "../data/loader.js";
import { disclaimer, money, pct, ratio, sum } from "../analysis/metrics.js";
export function growthSnapshot(segment?:string):string {
 const search=data.search.filter(row=>!segment||row.segment===segment),ads=data.ads.filter(row=>!segment||row.segment===segment),conversions=data.conversions.filter(row=>!segment||row.segment===segment);
 const impressions=sum(search,"impressions"),clicks=sum(search,"clicks"),spend=sum(ads,"spend"),leads=sum(conversions,"leads"),mqls=sum(conversions,"mqls"),sqls=sum(conversions,"sqls"),pipeline=sum(conversions,"estimated_pipeline"),previous=sum(search,"previous_period"),growth=ratio(sum(search,"current_period")-previous,previous);
 const segments=[...new Set(conversions.map(row=>row.segment))].map(name=>{const rows=conversions.filter(row=>row.segment===name);return {name,pipeline:sum(rows,"estimated_pipeline")}}).sort((a,b)=>b.pipeline-a.pipeline);
 const paidSqls=sum(ads,"sqls"),best=[...ads].sort((a,b)=>ratio(b.estimated_pipeline,b.spend)-ratio(a.estimated_pipeline,a.spend))[0];
 return `# Growth Snapshot${segment?` — ${segment}`:""}\n\n> ${disclaimer}\n\n## Executive readout\n\nOrganic demand ${growth>=0?"grew":"fell"} **${pct(Math.abs(growth))}** period over period. Marketing recorded **${sqls} SQLs** and **${money(pipeline)} estimated pipeline**. ${segments[0]?`**${segments[0].name}** has the largest attributed pipeline.`:""}\n\n| Signal | Result |\n|---|---:|\n| Organic impressions / clicks / CTR | ${impressions.toLocaleString()} / ${clicks.toLocaleString()} / ${pct(ratio(clicks,impressions))} |\n| Paid spend / clicks | ${money(spend)} / ${sum(ads,"clicks").toLocaleString()} |\n| Leads → MQLs → SQLs | ${leads} → ${mqls} → ${sqls} |\n| Paid SQLs / paid cost per SQL | ${paidSqls} / ${paidSqls?money(spend/paidSqls):"Unavailable"} |\n| Estimated pipeline | ${money(pipeline)} |\n\n## What matters\n\n- **Strongest efficiency:** ${best?`${best.campaign} at ${ratio(best.estimated_pipeline,best.spend).toFixed(1)}x paid pipeline/spend.`:"No paid campaign data available."}\n- **Decision standard:** prioritize SQL, opportunity and pipeline quality over traffic or lead volume.\n- **Next step:** use the opportunity radar and paid audit before changing investment.`;
}
