import { data } from "../data/loader.js";
import { opportunityRadar } from "../analysis/opportunity.js";
import { decideMarketingAction } from "../analysis/marketingDecision.js";
import { disclaimer, money, ratio, sum } from "../analysis/metrics.js";
export function buildGrowthBet(opportunity?:string,segment?:string,budget=100000):string {
 const ranked=opportunityRadar(data.search,data.ads),picked=ranked.find(row=>segment?row.segment===segment:opportunity?row.title.toLowerCase().includes(opportunity.toLowerCase()):false)??ranked[0];if(!picked)return "# Growth Bet\n\nNo opportunity can be built until valid data is supplied.";
 const search=data.search.filter(row=>row.segment===picked.segment),ads=data.ads.filter(row=>row.segment===picked.segment),previous=sum(search,"previous_period"),growth=ratio(sum(search,"current_period")-previous,previous),leads=sum(ads,"leads"),sqls=sum(ads,"sqls"),pipeline=sum(ads,"estimated_pipeline"),spend=sum(ads,"spend"),theme=[...search].sort((a,b)=>b.current_period-a.current_period)[0]?.query??picked.segment;
 const decision=decideMarketingAction({searchGrowth:growth,commercialIntent:search.some(row=>row.commercial_intent==="high"),paidEvidence:ads.length>0,leads,sqls,pipeline,spend,enterpriseRelevant:true,targetAccountEngagement:true});
 const field=decision.fieldMotion?`Run a small peer event around the operating question behind **${theme}**; measure qualified accounts, meetings, opportunities and pipeline.`:"Do not force an event yet. Revisit after the validation test produces sufficient enterprise qualification.";
 return `# Growth Bet — ${picked.segment}\n\n> ${disclaimer}\n\n## Opportunity\n\n${picked.title}.\n\n## Observed evidence\n\n- Organic demand changed ${Math.round(growth*100)}% period over period.\n- Paid activity generated ${sqls} SQLs and ${money(pipeline)} estimated pipeline.\n- Paid pipeline/spend is ${spend?(pipeline/spend).toFixed(1):"unavailable"}x.\n- Strongest search theme: **${theme}**.\n\n## Hypothesis\n\n${picked.hypothesis} This is a hypothesis, not a market fact.\n\n## Decision\n\n**State:** ${decision.state}  \n**Confidence:** ${decision.confidence}  \n**Action:** ${decision.action}\n\n## Coordinated motion\n\n- **Paid:** deploy up to ${money(Math.round(budget*.55))} in weekly tranches against the strongest commercial theme.\n- **SEO/CRO:** improve or build the intent-matched landing page for ${theme}.\n- **Content:** answer the buyer's evaluation question with verified proof placeholders.\n- **Field:** ${field}\n- **Sales:** align a discovery guide and named-account follow-up to the same segment and use case.\n\n## Measurement\n\nPrimary: qualified opportunities and pipeline. Secondary: cost per SQL, lead→SQL, pipeline/spend and target-account engagement.\n\n## Review window\n\nWeekly guardrails; full decision at day 30. Human approval is required before any external action.`;
}
