import { data } from "../data/loader.js";
import { scorePaidCampaigns } from "../analysis/performance.js";
import { disclaimer, money, pct } from "../analysis/metrics.js";
const n=(v:number|null,f:(x:number)=>string)=>(v===null?"Unavailable":f(v));
export function paidPerformanceReview():string {
 const rows=scorePaidCampaigns(data.ads,data.conversions),best=rows[0],worst=rows.at(-1)!;
 const actions=rows.slice(0,5).map((r,index)=>`${index+1}. **${r.campaign}:** ${r.scaleScore>=65?"run a capped 20–25% scale test":r.scaleScore<30?"reduce or pause; fix qualification and message match":"hold spend and run a narrow validation test"}.`);
 return `# Performance Marketing Agent — Paid Performance Review\n\n> ${disclaimer}\n\n## Executive readout\n\n**${best.campaign}** has the strongest downstream quality (score ${best.scaleScore}/100). **${worst.campaign}** is the weakest. Scores are deterministic decision aids, not scientific certainty. Momentum is unavailable in this one-period paid dataset and receives the documented neutral input.\n\n${rows.map(r=>`### ${r.campaign}\n\n**SIGNAL:** ${money(r.spend)} spend → ${r.leads} leads → ${r.mqls} MQLs → ${r.sqls} SQLs → ${r.opportunities??"unavailable"} opportunities → ${money(r.estimated_pipeline)} estimated pipeline. CPL ${n(r.cpl,money)}; cost/SQL ${n(r.costPerSql,money)}; lead→SQL ${n(r.leadToSql,pct)}; pipeline/spend ${n(r.pipelinePerSpend,x=>`${x.toFixed(1)}x`)}.\n\n**COMMERCIAL INTERPRETATION:** ${r.sqls>=7?"Acquisition is producing credible downstream demand; consider controlled scaling.":r.sqls<=2?"Traffic or lead volume is misleading because qualification and pipeline are weak.":"Evidence is useful but not strong enough for an aggressive increase."}\n\n**ACTION:** ${r.scaleScore>=65?"Test a 20–25% increase with cost-per-SQL and pipeline guardrails.":r.scaleScore<30?"Do not scale; reduce or pause and fix intent/message match.":"Hold or run a narrow validation test."}`).join("\n\n")}\n\n## Next actions\n\n${actions.join("\n")}`;
}
export function budgetAllocator(incrementalBudget:number):string {
 const rows=scorePaidCampaigns(data.ads,data.conversions),deploy=Math.round(incrementalBudget*.85),reserve=incrementalBudget-deploy;
 const candidates=rows.filter(r=>r.sqls>0&&r.scaleScore>=30).slice(0,3),weight=candidates.reduce((total,r)=>total+r.scaleScore,0);
 const allocations=candidates.map((r,index)=>{const amount=index===candidates.length-1?deploy-candidates.slice(0,-1).reduce((total,x)=>total+Math.round(deploy*x.scaleScore/weight),0):Math.round(deploy*r.scaleScore/weight);return {r,amount}});
 const allocationText=allocations.length?allocations.map(({r,amount})=>`### ${money(amount)} — ${r.campaign}\n**Why:** score ${r.scaleScore}/100; ${r.sqls} SQLs; ${n(r.costPerSql,money)} cost/SQL; ${n(r.pipelinePerSpend,x=>`${x.toFixed(1)}x`)} pipeline/spend.  \n**Confidence:** ${r.scaleScore>=65?"HIGH":r.scaleScore>=45?"MEDIUM":"LOW"}  \n**Guardrail:** release incrementally and preserve cost-per-SQL and pipeline efficiency.`).join("\n\n"):"No campaign qualifies for incremental deployment; retain the full amount pending validation.";
 const reduce=rows.filter(r=>r.scaleScore<30||r.sqls===0);
 return `# Budget Allocator\n\n> ${disclaimer}\n\n## Available budget\n\n**${money(incrementalBudget)}**\n\n## Recommended allocation\n\n${allocationText}\n\n### ${money(allocations.length?reserve:incrementalBudget)} — Validation reserve\n**Why:** preserve optionality until observed SQL and pipeline quality justify release.\n\n## Reduce / reallocate\n\n${reduce.length?reduce.map(r=>`- **${r.campaign}:** ${r.sqls===0?"no SQLs":"weak composite score"}; do not add incremental budget.`).join("\n"):"- No campaign currently meets the deterministic reduction threshold."}\n\nAllocations are calculated from the uploaded campaign scores. Human approval is required before any budget change.`;
}
export function designPaidExperiment(segment:string,opportunity:string,budget?:number):string {
 const amount=budget??15000;
 return `# Paid Experiment — ${opportunity}\n\n> ${disclaimer}\n\n**HYPOTHESIS**  \nA ${opportunity}-specific proposition will produce stronger qualified demand than broad category messaging.\n\n**SEGMENT / BUYER**  \n${segment}; use the operator-supplied persona and account definition before launch.\n\n**AUDIENCE**  \nNamed accounts or tightly defined buyers with relevant responsibility; exclude jobs, free, educational and irrelevant intent.\n\n**CAMPAIGN THEME**  \nOutcome-led ${opportunity}, supported only by verified claims.\n\n**LANDING PAGE REQUIRED**  \nYes — dedicated message match, problem, approach, proof placeholders and a clear next step.\n\n**BUDGET / DURATION**  \n${money(amount)} over 30 days, released in weekly tranches.\n\n**PRIMARY SUCCESS METRIC**  \nCost per SQL.\n\n**SECONDARY METRICS**  \nLead→SQL, opportunities, pipeline/spend and landing-page conversion.\n\n**SCALE CRITERIA**  \nAt least three SQLs, lead→SQL ≥15%, and pipeline/spend ≥30x after sufficient volume.\n\n**KILL CRITERIA**  \nPause or reposition after 150 qualified clicks if there are no SQLs, or if lead→SQL remains below 8%.\n\n**REVIEW WINDOW**  \nWeekly guardrail review; final decision at day 30. Human approval required for changes.`;
}
